description: Entity representing a list of <<resourcePathName|!singularize>>
get:
  description: |
    Get the list of <<resourcePathName|!singularize>>.
  responses:
    200:
      body:
        application/json:
put:
  description: |
    Creates new entity of <<resourcePathName|!singularize>>
  responses:
    200:
      body:
        application/json:
