#%RAML 1.0
title: Advanced Rest Client
uses:
  DataTypes: !include types/data-types.raml
version: v2
baseUri: https://api.advancedrestclient.com/{version}
description: |
  A backend API for Advanced Rest Client APP.
  The API is based on Google Cloud Endpoinds. Therefore OAuth2 authentication using Google account is required.
  All request are restricted to the authorized user. Valid Bearer token in the Authorization header is required.
mediaType: application/json
protocols: HTTPS
securitySchemes:
  - oauth_2_0: !include security-schemes/oauth_2_0.raml
resourceTypes:
  collection: !include types/requests-collection.raml
  collection-item: !include types/requests-collection-item.raml
securedBy: [ oauth_2_0: {scopes: [PROFILE]}]
schemas:
 - requestObject: !include schemas/request-object.schema
 - projectObject: !include schemas/project-object.schema
traits:
  paged: !include traits/paged.raml
  projected: !include traits/projected.raml
types:
/session:
  description: An information about current user session.
  get:
    responses:
      200:
        body:
          application/json:
            type: DataTypes.SessionState
/request:
  description: An endpoint used to read, store or delete user endpoinds data from the server
  get:
    description: Reads a list of all the requests available to the user. This may include shared with the user requests.
    is: [paged, projected]
  put:
    description: Stores a new RequestObject in the datastore.
  /{requestId}:
    description: |
      Endpoint represent a data related to the stored request.
      By default this endpoint will return a RequestObject with all HARs associated with it. Use projection without 'har' property included to retreive only the main definition of the request (body, method, url, payload) without requests history.

    delete:
      description: Removes user endpoint.
    post:
      description: Updates user endpoint
    get:
      description: Retreives single saved request definition.
      is: [projected]
    /har:
      get:
        description: Retreives a list of HAR objects related to the request
        is: [paged, projected]
      delete:
        description: Deletes all HAR data for selected endpoint
      /{harId}:
        post:
          description: Updates a HAR data.
        delete:
          description: Deletes particular HAR object definition.
