#%RAML 1.0
title: Advanced Rest Client
version: v1
baseUri: https://chromerestclient.appspot.com/
description: A kind of response.
types:
  AppResponse:
    type: object
    description: |
      App response is a base response object from the server.
      Every other response from the serwer must extend this base object.
    properties:
      kind:
        type: string
        description: A type representation for the response object. Kind values are have kind# prefix and datastore class name.
  SessionState:
    type: object
    description: |
      Session state represents an information if the user have session set on server.
      The response is kind#SessionState
    properties:
      uid:
        type: string
        description: User database ID
      hasSession:
        type: boolean
        description: A flag indicating if the user have active session.
  ResponseError:
    type: AppResponse
    description: If there was an error during the request there will be error property set to true.
    properties:
      error:
        type: boolean
        default: true
        required: true
        description: A flag set to response indicating that this is error message.
      code:
        type: number
        required: true
        description: Error code ID.
      message?:
        type: string
        description: Optional message explaining the error.
  RequestItem:
    type: object
    properties:
      id: number
      name:
        type: string
        description: A name for the request item
      url:
        type: string
        description: An URL for the request item
      payload:
        type: string
        description: A payload value for the request item
      method:
        type: string
        description: HTTP method name
      aid:
        type: string
        description: |
          Application uuid.
          Every apllication has own generated UUID. This value will be used to to associate items with the app.
      
/helloWorld:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message" : "Hello World"
              }
