CodeMirror.defineMode("javascript",function(I,J){function y(a,d){for(var c=!1,i;(i=a.next())!=null;){if(i==d&&!c)return!1;c=!c&&i=="\\"}return c}function k(a,d,c){o=a;z=c;return d}function q(a,d){var c=a.next();if(c=='"'||c=="'")return c=K(c),d.tokenize=c,c(a,d);else if(/[\[\]{}\(\),;\:\.]/.test(c))return k(c);else if(c=="0"&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),k("number","number");else if(/\d/.test(c))return a.match(/^\d*(?:\.\d*)?(?:e[+\-]?\d+)?/),k("number","number");else if(c=="/")return a.eat("*")?
(c=L,d.tokenize=c,c(a,d)):a.eat("/")?(a.skipToEnd(),k("comment","comment")):d.reAllowed?(y(a,"/"),a.eatWhile(/[gimy]/),k("regexp","string")):(a.eatWhile(t),k("operator",null,a.current()));else if(t.test(c))return a.eatWhile(t),k("operator",null,a.current());else{a.eatWhile(/[\w\$_]/);var c=a.current(),i=A.propertyIsEnumerable(c)&&A[c];return i?k(i.type,i.style,c):k("variable","variable",c)}}function K(a){return function(d,c){if(!y(d,a))c.tokenize=q;return k("string","string")}}function L(a,d){for(var c=
!1,i;i=a.next();){if(i=="/"&&c){d.tokenize=q;break}c=i=="*"}return k("comment","comment")}function B(a,d,c,i,b,e){this.indented=a;this.column=d;this.type=c;this.prev=b;this.info=e;if(i!=null)this.align=i}function m(){for(var a=arguments.length-1;a>=0;a--)e.cc.push(arguments[a])}function b(){m.apply(null,arguments);return!0}function u(a){var d=e.state;if(d.context){e.marked="def";for(var c=d.localVars;c;c=c.next)if(c.name==a)return;d.localVars={name:a,next:d.localVars}}}function C(){if(!e.state.context)e.state.localVars=
M;e.state.context={prev:e.state.context,vars:e.state.localVars}}function D(){e.state.localVars=e.state.context.vars;e.state.context=e.state.context.prev}function h(a,d){var c=function(){var c=e.state;c.lexical=new B(c.indented,e.stream.column(),a,null,c.lexical,d)};c.lex=!0;return c}function f(){var a=e.state;if(a.lexical.prev){if(a.lexical.type==")")a.indented=a.lexical.indented;a.lexical=a.lexical.prev}}function g(a){return function(d){return d==a?b():a==";"?m():b(arguments.callee)}}function n(a){if(a==
"var")return b(h("vardef"),v,g(";"),f);if(a=="keyword a")return b(h("form"),j,n,f);if(a=="keyword b")return b(h("form"),n,f);if(a=="{")return b(h("}"),w,f);if(a==";")return b();if(a=="function")return b(x);if(a=="for")return b(h("form"),g("("),h(")"),N,g(")"),f,n,f);if(a=="variable")return b(h("stat"),O);if(a=="switch")return b(h("form"),j,h("}","switch"),g("{"),w,f,f);if(a=="case")return b(j,g(":"));if(a=="default")return b(g(":"));if(a=="catch")return b(h("form"),C,g("("),E,g(")"),n,f,D);return m(h("stat"),
j,g(";"),f)}function j(a){if(F.hasOwnProperty(a))return b(l);if(a=="function")return b(x);if(a=="keyword c")return b(j);if(a=="(")return b(h(")"),j,g(")"),f,l);if(a=="operator")return b(j);if(a=="[")return b(h("]"),r(j,"]"),f,l);if(a=="{")return b(h("}"),r(P,"}"),f,l);return b()}function l(a,d){if(a=="operator"&&/\+\+|--/.test(d))return b(l);if(a=="operator")return b(j);if(a!=";"){if(a=="(")return b(h(")"),r(j,")"),f,l);if(a==".")return b(Q,l);if(a=="[")return b(h("]"),j,g("]"),f,l)}}function O(a){if(a==
":")return b(f,n);return m(l,g(";"),f)}function Q(a){if(a=="variable")return e.marked="property",b()}function P(a){if(a=="variable")e.marked="property";if(F.hasOwnProperty(a))return b(g(":"),j)}function r(a,d){function c(i){if(i==",")return b(a,c);if(i==d)return b();return b(g(d))}return function(i){return i==d?b():m(a,c)}}function w(a){if(a=="}")return b();return m(n,w)}function v(a,d){if(a=="variable")return u(d),b(G);return b()}function G(a,d){if(d=="=")return b(j,G);if(a==",")return b(v)}function N(a){if(a==
"var")return b(v,s);if(a==";")return m(s);if(a=="variable")return b(R);return m(s)}function R(a,d){if(d=="in")return b(j);return b(l,s)}function s(a,d){if(a==";")return b(H);if(d=="in")return b(j);return b(j,g(";"),H)}function H(a){a!=")"&&b(j)}function x(a,d){if(a=="variable")return u(d),b(x);if(a=="(")return b(h(")"),C,r(E,")"),f,n,D)}function E(a,d){if(a=="variable")return u(d),b()}var p=I.indentUnit,S=J.json,A=function(){function a(a){return{type:a,style:"keyword"}}var d=a("keyword a"),c=a("keyword b"),
b=a("keyword c"),e=a("operator"),f={type:"atom",style:"atom"};return{"if":d,"while":d,"with":d,"else":c,"do":c,"try":c,"finally":c,"return":b,"break":b,"continue":b,"new":b,"delete":b,"throw":b,"var":a("var"),"function":a("function"),"catch":a("catch"),"for":a("for"),"switch":a("switch"),"case":a("case"),"default":a("default"),"in":e,"typeof":e,"instanceof":e,"true":f,"false":f,"null":f,undefined:f,NaN:f,Infinity:f}}(),t=/[+\-*&%=<>!?|]/,o,z,F={atom:!0,number:!0,variable:!0,string:!0,regexp:!0},e=
{state:null,column:null,marked:null,cc:null},M={name:"this",next:{name:"arguments"}};f.lex=!0;return{startState:function(a){return{tokenize:q,reAllowed:!0,cc:[],lexical:new B((a||0)-p,0,"block",!1),localVars:null,context:null,indented:0}},token:function(a,d){if(a.sol()){if(!d.lexical.hasOwnProperty("align"))d.lexical.align=!1;d.indented=a.indentation()}if(a.eatSpace())return null;var c=d.tokenize(a,d);if(o=="comment")return c;d.reAllowed=o=="operator"||o=="keyword c"||o.match(/^[\[{}\(,;:]$/);var b;
a:{var f=o,h=z,g=d.cc;e.state=d;e.stream=a;e.marked=null;e.cc=g;if(!d.lexical.hasOwnProperty("align"))d.lexical.align=!0;for(;;)if((g.length?g.pop():S?j:n)(f,h)){for(;g.length&&g[g.length-1].lex;)g.pop()();if(e.marked){b=e.marked;break a}if(b=f=="variable")b:{for(b=d.localVars;b;b=b.next)if(b.name==h){b=!0;break b}b=void 0}if(b){b="variable-2";break a}b=c;break a}}return b},indent:function(a,b){if(a.tokenize!=q)return 0;var c=b&&b.charAt(0),e=a.lexical,f=e.type,g=c==f;return f=="vardef"?e.indented+
4:f=="form"&&c=="{"?e.indented:f=="stat"||f=="form"?e.indented+p:e.info=="switch"&&!g?e.indented+(/^(?:case|default)\b/.test(b)?p:2*p):e.align?e.column+(g?0:1):e.indented+(g?0:p)},electricChars:":{}"}});CodeMirror.defineMIME("text/javascript","javascript");CodeMirror.defineMIME("application/json",{name:"javascript",json:!0});