/* Compiled using Google Closure Compiler http://closure-compiler.appspot.com/ */
var CodeMirror=function(){function o(a,b){var c,d,e;function g(a){return 0<=a&&a<q.size}function h(a){for(var b=q;!b.lines;)for(var n=0;;++n){var c=b.children[n],d=c.chunkSize();if(a<d){b=c;break}a-=d}return b.lines[a]}function i(a,b){fa=!0;for(var n=b-a.height,c=a;c;c=c.parent)c.height+=n}function t(a){var b={line:0,ch:0};Ib(b,{line:q.size-1,ch:h(q.size-1).text.length},qa(a),b,b);ra=!0}function z(a){var b=ma[a.keyCode],n=V[l.keyMap].auto,c,d;if(null==b||a.altGraphKey){if(n)l.keyMap=n;return null}a.altKey&&
(b="Alt-"+b);a.ctrlKey&&(b="Ctrl-"+b);a.metaKey&&(b="Cmd-"+b);a.shiftKey&&(c=y("Shift-"+b,l.extraKeys,l.keyMap))?d=!0:c=y(b,l.extraKeys,l.keyMap);"string"==typeof c&&(c=Ba.propertyIsEnumerable(c)?Ba[c]:null);if(b=n)if(!(b=c))b=ma[a.keyCode],b=!("Ctrl"==b||"Alt"==b||"Shift"==b||"Mod"==b);if(b)l.keyMap=n;if(!c)return!1;d?(n=Y,Y=null,c(I),Y=n):c(I);x(a);return!0}function C(){if(!l.readOnly){if(!ca){if(l.onFocus)l.onFocus(I);ca=!0;-1==J.className.search(/\bCodeMirror-focused\b/)&&(J.className+=" CodeMirror-focused");
La||la(!0)}bb();Jb()}}function U(){if(ca){if(l.onBlur)l.onBlur(I);ca=!1;J.className=J.className.replace(" CodeMirror-focused","")}clearInterval(ob);setTimeout(function(){ca||(Y=null)},150)}function Ib(a,b,c,d,e){if(da){var h=[];q.iter(a.line,b.line+1,function(a){h.push(a.text)});for(da.addChange(a.line,c.length,h);da.done.length>l.undoDepth;)da.done.shift()}Kb(a,b,c,d,e)}function Lb(a,b){var c=a.pop();if(c){var d=[],e=c.start+c.added;q.iter(c.start,e,function(a){d.push(a.text)});b.push({start:c.start,
added:c.old.length,old:d});var Ha=N({line:c.start+c.old.length-1,ch:Ma(d[d.length-1],c.old[c.old.length-1])});Kb({line:c.start,ch:0},{line:e-1,ch:h(e-1).text.length},c.old,Ha,Ha);ra=!0}}function Kb(a,b,n,e,Ka){var Ha=!1,g=sa.length;l.lineWrapping||q.iter(a.line,b.line,function(a){if(a.text.length==g)return Ha=!0});if(a.line!=b.line||1<n.length)fa=!0;var Z=b.line-a.line,K=h(a.line),f=h(b.line);if(0==a.ch&&0==b.ch&&""==n[n.length-1]){var k=[],K=null;a.line?(K=h(a.line-1),K.fixMarkEnds(f)):f.fixMarkStarts();
for(var t=0,j=n.length-1;t<j;++t)k.push(r.inheritMarks(n[t],K));Z&&q.remove(a.line,Z,Na);k.length&&q.insert(a.line,k)}else if(K==f)if(1==n.length)K.replace(a.ch,b.ch,n[0]);else{f=K.split(b.ch,n[n.length-1]);K.replace(a.ch,null,n[0]);K.fixMarkEnds(f);k=[];t=1;for(j=n.length-1;t<j;++t)k.push(r.inheritMarks(n[t],K));k.push(f);q.insert(a.line+1,k)}else if(1==n.length)K.replace(a.ch,null,n[0]),f.replace(null,b.ch,""),K.append(f),q.remove(a.line+1,Z,Na);else{k=[];K.replace(a.ch,null,n[0]);f.replace(null,
b.ch,n[n.length-1]);K.fixMarkEnds(f);t=1;for(j=n.length-1;t<j;++t)k.push(r.inheritMarks(n[t],K));1<Z&&q.remove(a.line+1,Z-1,Na);q.insert(a.line+1,k)}if(l.lineWrapping){var s=w.clientWidth/pb()-3;q.iter(a.line,a.line+n.length,function(a){if(!a.hidden){var H=Math.ceil(a.text.length/s)||1;H!=a.height&&i(a,H)}})}else q.iter(a.line,t+n.length,function(a){a=a.text;if(a.length>g)sa=a,g=a.length,ta=null,Ha=!1}),Ha&&(g=0,sa="",ta=null,q.iter(0,q.size,function(a){a=a.text;if(a.length>g)g=a.length,sa=a}));f=
[];Z=n.length-Z-1;t=0;for(k=ga.length;t<k;++t)j=ga[t],j<a.line?f.push(j):j>b.line&&f.push(j+Z);t=a.line+Math.min(n.length,500);lc(a.line,t);f.push(t);ga=f;qb(100);Q.push({from:a.line,to:b.line+1,diff:Z});a={from:a,to:b,text:n};if(Oa){for(n=Oa;n.next;n=n.next);n.next=a}else Oa=a;Pa(e,Ka,c.line<=Math.min(b.line,b.line+Z)?c.line:c.line+Z,d.line<=Math.min(b.line,b.line+Z)?d.line:d.line+Z);$.style.height=q.height*na()+2*G.offsetTop+"px"}function ha(a,b,n){function e(c){if(ea(c,b))return c;if(!ea(n,c))return Ka;
var d=c.line+a.length-(n.line-b.line)-1,nb=c.ch;c.line==n.line&&(nb+=a[a.length-1].length-(n.ch-(n.line==b.line?b.ch:0)));return{line:d,ch:nb}}var b=N(b),n=n?N(n):b,a=qa(a),Ka;Mb(a,b,n,function(a){Ka=a;return{from:e(c),to:e(d)}});return Ka}function Qa(a,b){Mb(qa(a),c,d,function(a){return"end"==b?{from:a,to:a}:"start"==b?{from:c,to:c}:{from:c,to:a}})}function Mb(a,b,c,d){d=d({line:b.line+a.length-1,ch:1==a.length?a[0].length+b.ch:a[a.length-1].length});Ib(b,c,a,d.from,d.to)}function Nb(a,b){var c=
a.line,d=b.line;if(c==d)return h(c).text.slice(a.ch,b.ch);var e=[h(c).text.slice(a.ch)];q.iter(c+1,d,function(a){e.push(a.text)});e.push(h(d).text.slice(0,b.ch));return e.join("\n")}function cb(){return Nb(c,d)}function bb(){rb||sb.set(l.pollInterval,function(){tb();pa();ca&&bb();ub()})}function Ra(){function a(){tb();!pa()&&!b?(b=!0,sb.set(60,a)):(rb=!1,bb());ub()}var b=!1;rb=!0;sb.set(20,a)}function pa(){if(La||!ca||db(F))return!1;var a=F.value;if(a==ua)return!1;Y=null;for(var b=0,n=Math.min(ua.length,
a.length);b<n&&ua[b]==a[b];)++b;b<ua.length?c={line:c.line,ch:c.ch-(ua.length-b)}:vb&&s(c,d)&&(d={line:d.line,ch:Math.min(h(d.line).text.length,d.ch+(a.length-b))});Qa(a.slice(b),"end");ua=a;return!0}function la(a){if(s(c,d)){if(a)ua=F.value=""}else ua="",F.value=cb(),F.select()}function Ca(){l.readOnly||F.focus()}function mc(){if(ia.getBoundingClientRect){var a=ia.getBoundingClientRect();if(!(va&&a.top==a.bottom)){var b=window.innerHeight||Math.max(document.body.offsetHeight,document.documentElement.offsetHeight);
(0>a.top||a.bottom>b)&&ia.scrollIntoView()}}}function Ob(){var a=Sa(e?c:d),b=l.lineWrapping?Math.min(a.x,G.offsetWidth):a.x;return Pb(b,a.y,b,a.yBot)}function Pb(a,b,c,d){var e=G.offsetLeft,h=G.offsetTop,g=na(),b=b+h,d=d+h,a=a+e,c=c+e,f=w.clientHeight,i=w.scrollTop,e=!1,h=!0;if(b<i)w.scrollTop=Math.max(0,b-2*g),e=!0;else if(d>i+f)w.scrollTop=d+g-f,e=!0;b=w.clientWidth;d=w.scrollLeft;g=l.fixedGutter?W.clientWidth:0;if(a<d+g)50>a&&(a=0),w.scrollLeft=Math.max(0,a-10-g),e=!0;else if(c>b+d-3)w.scrollLeft=
c+10-b,e=!0,c>$.clientWidth&&(h=!1);if(e&&l.onScroll)l.onScroll(I);return h}function Qb(){var a=na(),b=w.scrollTop-G.offsetTop,c=Math.max(0,Math.floor(b/a)),a=Math.ceil((b+w.clientHeight)/a);return{from:O(q,c),to:O(q,a)}}function Ta(a,b){if(w.clientWidth){var c=Qb();if(!(!0!==a&&0==a.length&&c.from>=R&&c.to<=aa)){var d=Math.max(c.from-100,0),c=Math.min(q.size,c.to+100);R<d&&20>d-R&&(d=R);aa>c&&20>aa-c&&(c=Math.min(q.size,aa));for(var e=!0===a?[]:nc([{from:R,to:aa,domStart:0}],a),h=0,g=0;g<e.length;++g){var f=
e[g];if(f.from<d)f.domStart+=d-f.from,f.from=d;if(f.to>c)f.to=c;f.from>=f.to?e.splice(g--,1):h+=f.to-f.from}if(h!=c-d){e.sort(function(a,b){return a.domStart-b.domStart});var K=na(),h=W.style.display;ba.style.display=W.style.display="none";oc(d,c,e);ba.style.display="";(g=d!=R||c!=aa||Rb!=w.clientHeight+K)&&(Rb=w.clientHeight+K);R=d;aa=c;Ua=j(q,d);eb.style.top=Ua*K+"px";$.style.height=q.height*K+2*G.offsetTop+"px";if(ba.childNodes.length!=aa-R)throw Error("BAD PATCH! "+JSON.stringify(e)+" size="+
(aa-R)+" nodes="+ba.childNodes.length);if(l.lineWrapping){ta=w.clientWidth;var k=ba.firstChild;q.iter(R,aa,function(a){if(!a.hidden){var b=Math.round(k.offsetHeight/K)||1;a.height!=b&&(i(a,b),fa=!0)}k=k.nextSibling})}else null==ta&&(ta=wb(sa)),ta>w.clientWidth?(G.style.width=ta+"px",$.style.width="",$.style.width=w.scrollWidth+"px"):G.style.width=$.style.width="";W.style.display=h;(g||fa)&&Sb();Tb();if(!b&&l.onUpdate)l.onUpdate(I);return!0}}}else R=aa=Ua=0}function nc(a,b){for(var c=0,d=b.length||
0;c<d;++c){for(var e=b[c],h=[],g=e.diff||0,f=0,i=a.length;f<i;++f){var k=a[f];e.to<=k.from&&e.diff?h.push({from:k.from+g,to:k.to+g,domStart:k.domStart}):e.to<=k.from||e.from>=k.to?h.push(k):(e.from>k.from&&h.push({from:k.from,to:e.from,domStart:k.domStart}),e.to<k.to&&h.push({from:e.to+g,to:k.to+g,domStart:k.domStart+(e.to-k.from)}))}a=h}return a}function oc(a,b,n){if(n.length){for(var e=function(a){var b=a.nextSibling;a.parentNode.removeChild(a);return b},h=0,g=ba.firstChild,f=0;f<n.length;++f){for(var k=
n[f];k.domStart>h;)g=e(g),h++;for(var i=0,k=k.to-k.from;i<k;++i)g=g.nextSibling,h++}for(;g;)g=e(g)}else ba.innerHTML="";var l=n.shift(),g=ba.firstChild,i=a,t=c.line,j=d.line,s=t<a&&j>=a,p=Da.createElement("div");q.iter(a,b,function(a){var b=null,H=null;if(s){if(b=0,j==i)s=!1,H=d.ch}else if(t==i)j==i?(b=c.ch,H=d.ch):(s=!0,b=c.ch);l&&l.to==i&&(l=n.shift());!l||l.from>i?(p.innerHTML=a.hidden?"<pre></pre>":a.getHTML(b,H,!0,xb),ba.insertBefore(p.firstChild,g)):g=g.nextSibling;++i})}function Sb(){if(l.gutter||
l.lineNumbers){var a=eb.offsetHeight,b=w.clientHeight;W.style.height=(2>a-b?b:a)+"px";var c=[],d=R;q.iter(R,Math.max(aa,R+1),function(a){if(a.hidden)c.push("<pre></pre>");else{var b=a.gutterMarker,H=l.lineNumbers?d+l.firstLineNumber:null;b&&b.text?H=b.text.replace("%N%",null!=H?H:""):null==H&&(H="\u00a0");c.push(b&&b.style?'<pre class="'+b.style+'">':"<pre>",H);for(b=1;b<a.height;++b)c.push("<br/>&#160;");c.push("</pre>")}++d});W.style.display="none";Va.innerHTML=c.join("");for(var a=(""+q.size).length,
b=Va.firstChild,e=b.textContent||b.innerText||b.nodeValue||"",h="";e.length+h.length<a;)h+="\u00a0";h&&b.insertBefore(Da.createTextNode(h),b.firstChild);W.style.display="";G.style.marginLeft=W.offsetWidth+"px";fa=!1}}function Tb(){var a=e?c:d;na();var a=Sa(a,!0),b=A(J),n=A(ba);Wa.style.top=a.y+n.top-b.top+"px";Wa.style.left=a.x+n.left-b.left+"px";s(c,d)?(ia.style.top=a.y+"px",ia.style.left=(l.lineWrapping?Math.min(a.x,G.offsetWidth):a.x)+"px",ia.style.display=""):ia.style.display="none"}function wa(a,
b){var c=Y&&N(Y);c&&(ea(c,a)?a=c:ea(b,c)&&(b=c));Pa(a,b);fb=!0}function Pa(a,b,n,h){gb=null;if(null==n)n=c.line,h=d.line;if(!s(c,a)||!s(d,b)){if(ea(b,a))var g=b,b=a,a=g;a.line!=n&&(a=hb(a,n,c.ch));b.line!=h&&(b=hb(b,h,d.ch));s(a,b)?e=!1:s(a,d)?e=!1:s(b,c)&&(e=!0);s(a,b)?s(c,d)||Q.push({from:n,to:h+1}):s(c,d)?Q.push({from:a.line,to:b.line+1}):(s(a,c)||(a.line<n?Q.push({from:a.line,to:Math.min(b.line,n)+1}):Q.push({from:n,to:Math.min(h,a.line)+1})),s(b,d)||(b.line<h?Q.push({from:Math.max(n,a.line),
to:h+1}):Q.push({from:Math.max(a.line,h),to:b.line+1})));c=a;d=b;xa=!0}}function hb(a,b,c){function d(b){for(var e=a.line+b,kc=1==b?q.size:-1;e!=kc;){var g=h(e);if(!g.hidden){b=a.ch;if(b>c||b>g.text.length)b=g.text.length;return{line:e,ch:b}}e+=b}}return!h(a.line).hidden?a:a.line>=b?d(1)||d(-1):d(-1)||d(1)}function ya(a,b,c){a=N({line:a,ch:b||0});(c?wa:Pa)(a,a)}function ib(a){return Math.max(0,Math.min(a,q.size-1))}function N(a){if(0>a.line)return{line:0,ch:0};if(a.line>=q.size)return{line:q.size-
1,ch:h(q.size-1).text.length};var b=a.ch,c=h(a.line).text.length;return null==b||b>c?{line:a.line,ch:c}:0>b?{line:a.line,ch:0}:a}function yb(a,b){function n(b){if(i==(0>a?0:k.text.length)){if(b=!b)a:{for(var b=f+a,c=0>a?-1:q.size;b!=c;b+=a){var d=h(b);if(!d.hidden){f=b;k=d;b=!0;break a}}b=void 0}if(b)i=0>a?k.text.length:0;else return!1}else i+=a;return!0}var g=e?c:d,f=g.line,i=g.ch,k=h(f);if("char"==b)n();else if("column"==b)n(!0);else if("word"==b)for(g=!1;!(0>a)||n();){if(Ia(k.text.charAt(i)))g=
!0;else if(g){0>a&&(a=1,n());break}if(0<a&&!n())break}return{line:f,ch:i}}function Ub(a){for(var b=h(a.line).text,c=a.ch,d=a.ch;0<c&&Ia(b.charAt(c-1));)--c;for(;d<b.length&&Ia(b.charAt(d));)++d;wa({line:a.line,ch:c},{line:a.line,ch:d})}function pc(a){wa({line:a,ch:0},{line:a,ch:h(a).text.length})}function jb(a,b){b||(b="add");if("smart"==b)if(L.indent)var n=kb(a);else b="prev";var e=h(a),g=e.indentation(l.tabSize),f=e.text.match(/^\s*/)[0],i;"prev"==b?i=a?h(a-1).indentation(l.tabSize):0:"smart"==
b?i=L.indent(n,e.text.slice(f.length),e.text):"add"==b?i=g+l.indentUnit:"subtract"==b&&(i=g-l.indentUnit);i=Math.max(0,i);if(i-g){g="";n=0;if(l.indentWithTabs)for(e=Math.floor(i/l.tabSize);e;--e)n+=l.tabSize,g+="\t";for(;n<i;)++n,g+=" "}else{if(c.line!=a&&d.line!=a)return;g=f}ha(g,{line:a,ch:0},{line:a,ch:f.length})}function Vb(){L=o.getMode(l,l.mode);q.iter(0,q.size,function(a){a.stateAfter=null});ga=[0];qb()}function qc(){var a=l.gutter||l.lineNumbers;W.style.display=a?"":"none";a?fa=!0:ba.parentNode.style.marginLeft=
0}function rc(){if(l.lineWrapping){J.className+=" CodeMirror-wrap";var a=w.clientWidth/pb()-3;q.iter(0,q.size,function(b){if(!b.hidden){var c=Math.ceil(b.text.length/a)||1;1!=c&&i(b,c)}});G.style.width=$.style.width=""}else J.className=J.className.replace(" CodeMirror-wrap",""),ta=null,sa="",q.iter(0,q.size,function(a){1!=a.height&&!a.hidden&&i(a,1);if(a.text.length>sa.length)sa=a.text});Q.push({from:0,to:q.size})}function Wb(){for(var a='<span class="cm-tab">',b=0;b<l.tabSize;++b)a+=" ";return a+
"</span>"}function sc(){xb=Wb();Ta(!0)}function Xb(){w.className=w.className.replace(/\s*cm-s-\w+/g,"")+l.theme.replace(/(^|\s)\s*/g," cm-s-")}function zb(){this.set=[]}function Ab(a,b,c){function d(a,b,c,H){h(a).addMark(new D(b,c,H,e.set))}var a=N(a),b=N(b),e=new zb;if(a.line==b.line)d(a.line,a.ch,b.ch,c);else{d(a.line,a.ch,null,c);for(var g=a.line+1,f=b.line;g<f;++g)d(g,null,null,c);d(b.line,null,b.ch,c)}Q.push({from:a.line,to:b.line+1});return e}function Yb(a,b){var c=a,d=a;"number"==typeof a?
d=h(ib(a)):c=X(a);if(null==c)return null;if(b(d,c))Q.push({from:c,to:c+1});else return null;return d}function Zb(a,b){return Yb(a,function(a,H){if(a.hidden!=b)return a.hidden=b,i(a,b?0:1),b&&(c.line==H||d.line==H)&&Pa(hb(c,c.line,c.ch),hb(d,d.line,d.ch)),fa=!0})}function wb(a){za.innerHTML="<pre><span>x</span></pre>";za.firstChild.firstChild.firstChild.nodeValue=a;return za.firstChild.firstChild.offsetWidth||10}function $b(a,b){var c="";l.lineWrapping&&(c=a.text.indexOf(" ",b+2),c=T(a.text.slice(b+
1,0>c?a.text.length:c+(va?5:0))));za.innerHTML="<pre>"+a.getHTML(null,null,!1,xb,b)+'<span id="CodeMirror-temp-'+ac+'">'+T(a.text.charAt(b)||" ")+"</span>"+c+"</pre>";var c=document.getElementById("CodeMirror-temp-"+ac),d=c.offsetTop,e=c.offsetLeft;if(va&&b&&0==d&&0==e)d=document.createElement("span"),d.innerHTML="x",c.parentNode.insertBefore(d,c.nextSibling),d=d.offsetTop;return{top:d,left:e}}function Sa(a,b){var c,d=na(),e=d*(j(q,a.line)-(b?Ua:0));if(0==a.ch)c=0;else{var g=$b(h(a.line),a.ch);c=
g.left;l.lineWrapping&&(e+=Math.max(0,g.top))}return{x:c,y:e,yBot:e+d}}function Bb(a,b){function c(a){a=$b(i,a);if(t){var b=Math.round(a.top/d);return Math.max(0,a.left+(b-s)*w.clientWidth)}return a.left}0>b&&(b=0);var d=na(),e=pb(),g=Ua+Math.floor(b/d),f=O(q,g);if(f>=q.size)return{line:q.size-1,ch:h(q.size-1).text.length};var i=h(f),k=i.text,t=l.lineWrapping,s=t?g-j(q,f):0;if(0>=a&&0==s)return{line:f,ch:0};for(var p=g=0,k=k.length,A,e=Math.min(k,Math.ceil((a+0.9*s*w.clientWidth)/e));;){var m=c(e);
if(m<=a&&e<k)e=Math.min(k,Math.ceil(1.2*e));else{A=m;k=e;break}}if(a>A)return{line:f,ch:k};e=Math.floor(0.8*k);m=c(e);m<a&&(g=e,p=m);for(;;){if(1>=k-g)return{line:f,ch:A-a>a-p?g:k};e=Math.ceil((g+k)/2);m=c(e);m>a?(k=e,A=m):(g=e,p=m)}}function bc(a){var a=Sa(a,!0),b=A(G);return{x:b.left+a.x,y:b.top+a.y,yBot:b.top+a.yBot}}function na(){if(null==Ea){Ea="<pre>";for(var a=0;49>a;++a)Ea+="x<br/>";Ea+="x</pre>"}a=ba.clientHeight;if(a==cc)return Cb;cc=a;za.innerHTML=Ea;Cb=za.firstChild.offsetHeight/50||1;
za.innerHTML="";return Cb}function pb(){if(w.clientWidth==dc)return ec;dc=w.clientWidth;return ec=wb("x")}function Ja(a,b){var c=A(w,!0),d,e;try{d=a.clientX,e=a.clientY}catch(g){return null}if(!b&&(d-c.left>w.clientWidth||e-c.top>w.clientHeight))return null;c=A(G,!0);return Bb(d-c.left,e-c.top)}function fc(a){function b(){var a=qa(F.value).join("\n");a!=h&&v(Qa)(a,"end");Wa.style.position="relative";F.style.cssText=g;La=!1;la(!0);bb()}var e=Ja(a);if(e&&!window.opera){(s(c,d)||ea(e,c)||!ea(e,d))&&
v(ya)(e.line,e.ch);var g=F.style.cssText;Wa.style.position="absolute";F.style.cssText="position: fixed; width: 30px; height: 30px; top: "+(a.clientY-5)+"px; left: "+(a.clientX-5)+"px; z-index: 1000; background: white; border-width: 0; outline: none; overflow: hidden; opacity: .05; filter: alpha(opacity=5);";La=!0;var h=F.value=cb();Ca();F.select();if(Xa){B(a);var f=p(window,"mouseup",function(){f();setTimeout(b,20)},!0)}else setTimeout(b,50)}}function Jb(){clearInterval(ob);var a=!0;ia.style.visibility=
"";ob=setInterval(function(){ia.style.visibility=(a=!a)?"":"hidden"},650)}function gc(a){function b(a,c,d){if(a.text)for(var e=a.styles,a=l?0:a.text.length-1,H,g=l?0:e.length-2,h=l?e.length:-2;g!=h;g+=2*t){var n=e[g];if(null!=e[g+1]&&e[g+1]!=m)a+=t*n.length;else for(var f=l?0:n.length-1,k=l?n.length:-1;f!=k;f+=t,a+=t)if(a>=c&&a<d&&o.test(H=n.charAt(f))){var i=Db[H];if(">"==i.charAt(1)==l)A.push(H);else{if(A.pop()!=i.charAt(0))return{pos:a,match:!1};if(!A.length)return{pos:a,match:!0}}}}}var g=e?c:
d,f=h(g.line),i=g.ch-1,k=0<=i&&Db[f.text.charAt(i)]||Db[f.text.charAt(++i)];if(k){k.charAt(0);for(var l=">"==k.charAt(1),t=l?1:-1,j=f.styles,s=i+1,k=0,p=j.length;k<p;k+=2)if(0>=(s-=j[k].length)){var m=j[k+1];break}for(var A=[f.text.charAt(i)],o=/[(){}[\]]/,k=g.line,p=l?Math.min(k+100,q.size):Math.max(-1,k-100);k!=p;k+=t){var f=h(k),r=k==g.line;if(r=b(f,r&&l?i+1:0,r&&!l?i:f.text.length))break}r||(r={pos:null,match:!1});var m=r.match?"CodeMirror-matchingbracket":"CodeMirror-nonmatchingbracket",w=Ab({line:g.line,
ch:i},{line:g.line,ch:i+1},m),u=null!=r.pos&&Ab({line:k,ch:r.pos},{line:k,ch:r.pos+1},m),g=v(function(){w.clear();u&&u.clear()});a?setTimeout(g,800):lb=g}}function hc(a){for(var b,c,d=a,a=a-40;d>a;--d){if(0==d)return 0;var e=h(d-1);if(e.stateAfter)return d;e=e.indentation(l.tabSize);if(null==c||b>e)c=d-1,b=e}return c}function kb(a){var b=hc(a),c=b&&h(b-1).stateAfter,c=c?u(L,c):M(L);q.iter(b,a,function(a){a.highlight(L,c,l.tabSize);a.stateAfter=u(L,c)});b<a&&Q.push({from:b,to:a});a<q.size&&!h(a).stateAfter&&
ga.push(a);return c}function lc(a,b){var c=kb(a);q.iter(a,b,function(a){a.highlight(L,c,l.tabSize);a.stateAfter=u(L,c)})}function tc(){for(var a=+new Date+l.workTime,b=ga.length;ga.length;){var c=h(R).stateAfter?ga.pop():R;if(!(c>=q.size)){var d=hc(c),e=d&&h(d-1).stateAfter,e=e?u(L,e):M(L),g=0,f=L.compareStates,k=!1,i=d,t=!1;q.iter(i,q.size,function(b){var d=b.stateAfter;if(+new Date>a)return ga.push(i),qb(l.workDelay),k&&Q.push({from:c,to:i+1}),t=!0;var h=b.highlight(L,e,l.tabSize);h&&(k=!0);b.stateAfter=
u(L,e);if(f){if(d&&f(d,e))return!0}else if(!1!==h||!d)g=0;else if(3<++g&&(!L.indent||L.indent(d,"")==L.indent(e,"")))return!0;++i});if(t)return;k&&Q.push({from:c,to:i+1})}}if(b&&l.onHighlightComplete)l.onHighlightComplete(I)}function qb(a){ga.length&&uc.set(a,v(tc))}function tb(){ra=fb=Oa=null;Q=[];xa=!1;Na=[]}function ub(){var a=!1,b;xa&&(a=!Ob());Q.length?b=Ta(Q,!0):(xa&&Tb(),fa&&Sb());a&&Ob();xa&&(mc(),Jb());ca&&!La&&(!0===ra||!1!==ra&&xa)&&la(fb);xa&&l.matchBrackets&&setTimeout(v(function(){lb&&
(lb(),lb=null);s(c,d)&&gc(!1)}),20);var e=Oa,a=Na;if(xa&&l.onCursorActivity)l.onCursorActivity(I);if(e&&l.onChange&&I)l.onChange(I,e);for(e=0;e<a.length;++e)a[e](I);if(b&&l.onUpdate)l.onUpdate(I)}function v(a){return function(){ic++||tb();try{var b=a.apply(this,arguments)}finally{--ic||ub()}return b}}var l={},Eb=o.defaults,Ya;for(Ya in Eb)Eb.hasOwnProperty(Ya)&&(l[Ya]=(b&&b.hasOwnProperty(Ya)?b:Eb)[Ya]);var Da=l.document,J=Da.createElement("div");J.className="CodeMirror"+(l.lineWrapping?" CodeMirror-wrap":
"");J.innerHTML='<div style="overflow: hidden; position: relative; width: 3px; height: 0px;"><textarea style="position: absolute; padding: 0; width: 1px;" wrap="off" autocorrect="off" autocapitalize="off"></textarea></div><div class="CodeMirror-scroll" tabindex="-1"><div style="position: relative"><div style="position: relative"><div class="CodeMirror-gutter"><div class="CodeMirror-gutter-text"></div></div><div class="CodeMirror-lines"><div style="position: relative"><div style="position: absolute; width: 100%; height: 0; overflow: hidden; visibility: hidden"></div><pre class="CodeMirror-cursor">&#160;</pre><div></div></div></div></div></div></div>';
a.appendChild?a.appendChild(J):a(J);var Wa=J.firstChild,F=Wa.firstChild,w=J.lastChild,$=w.firstChild,eb=$.firstChild,W=eb.firstChild,Va=W.firstChild,G=W.nextSibling.firstChild,za=G.firstChild,ia=za.nextSibling,ba=ia.nextSibling;Xb();if(/AppleWebKit/.test(navigator.userAgent)&&/Mobile\/\w+/.test(navigator.userAgent))F.style.width="0px";if(!Fa)G.draggable=!0;if(null!=l.tabindex)F.tabIndex=l.tabindex;if(!l.gutter&&!l.lineNumbers)W.style.display="none";try{wb("x")}catch(Fb){throw Fb.message.match(/runtime/i)&&
(Fb=Error("A CodeMirror inside a P-style element does not work in Internet Explorer. (innerHTML bug)")),Fb;}var sb=new k,uc=new k,ob,L,q=new m([new f([new r("")])]),ga,ca;Vb();c={line:0,ch:0};d={line:0,ch:0};e=!1;var Y,mb,Za,Gb,vb=!1,ra,fb,Q,Oa,xa,La,fa,Na,Ua=0,R=0,aa=0,Rb=0,lb,sa="",ta,xb=Wb();v(function(){t(l.value||"");ra=!1})();var da=new ja;p(w,"mousedown",v(function(a){function b(a){var c=Ja(a,!0);if(c&&!s(c,f)){ca||C();f=c;wa(h,c);ra=!1;var d=Qb();if(c.line>=d.to||c.line<d.from)k=setTimeout(v(function(){b(a)}),
150)}}Y=a.shiftKey?Y||(e?d:c):null;for(var g=a.target||a.srcElement;g!=J;g=g.parentNode)if(g.parentNode==$&&g!=eb)return;for(g=a.target||a.srcElement;g!=J;g=g.parentNode)if(g.parentNode==Va){if(l.onGutterClick)l.onGutterClick(I,oa(Va.childNodes,g)+R,a);return x(a)}var h=Ja(a);switch(E(a)){case 3:Xa&&!$a&&fc(a);return;case 2:h&&ya(h.line,h.ch,!0);return}if(h){ca||C();g=+new Date;if(Za&&Za.time>g-400&&s(Za.pos,h))return x(a),setTimeout(Ca,20),pc(h.line);if(mb&&mb.time>g-400&&s(mb.pos,h))return Za={time:g,
pos:h},x(a),Ub(h);mb={time:g,pos:h};var f=h,k;if(Aa&&!s(c,d)&&!ea(h,c)&&!ea(d,h)){if(Fa)G.draggable=!0;var i=p(Da,"mouseup",v(function(b){if(Fa)G.draggable=!1;Gb=!1;i();10>Math.abs(a.clientX-b.clientX)+Math.abs(a.clientY-b.clientY)&&(x(b),ya(h.line,h.ch,!0),Ca())}),!0);Gb=!0}else{x(a);ya(h.line,h.ch,!0);var t=p(Da,"mousemove",v(function(a){clearTimeout(k);x(a);b(a)}),!0),i=p(Da,"mouseup",v(function(a){clearTimeout(k);var b=Ja(a);b&&wa(h,b);x(a);Ca();ra=!0;t();i()}),!0)}}else(a.target||a.srcElement)==
w&&x(a)}));p(w,"dblclick",v(function(a){for(var b=a.target||a.srcElement;b!=J;b=b.parentNode)if(b.parentNode==Va)return x(a);if(b=Ja(a))Za={time:+new Date,pos:b},x(a),Ub(b)}));p(G,"dragstart",function(a){var b=cb();T(b);a.dataTransfer.setDragImage(S,0,0);a.dataTransfer.setData("Text",b)});p(G,"selectstart",x);Xa||p(w,"contextmenu",fc);p(w,"scroll",function(){Ta([]);if(l.fixedGutter)W.style.left=w.scrollLeft+"px";if(l.onScroll)l.onScroll(I)});p(window,"resize",function(){Ta(!0)});p(F,"keyup",v(function(a){if(!l.onKeyEvent||
!l.onKeyEvent(I,ka(a)))16==a.keyCode&&(Y=null)}));p(F,"input",Ra);p(F,"keydown",v(function(a){ca||C();var b=a.keyCode;if(va&&27==b)a.returnValue=!1;Y=16==b||a.shiftKey?Y||(e?d:c):null;if(!l.onKeyEvent||!l.onKeyEvent(I,ka(a)))b=z(a),window.opera&&(Hb=b?a.keyCode:null,!b&&($a?a.metaKey:a.ctrlKey)&&88==a.keyCode&&Qa(""))}));p(F,"keypress",v(function(a){if(window.opera&&a.keyCode==Hb)Hb=null,x(a);else if(!l.onKeyEvent||!l.onKeyEvent(I,ka(a)))if(!window.opera||a.which||!z(a))l.electricChars&&L.electricChars&&
(a=String.fromCharCode(null==a.charCode?a.keyCode:a.charCode),-1<L.electricChars.indexOf(a)&&setTimeout(v(function(){jb(d.line,"smart")}),75)),Ra()}));p(F,"focus",C);p(F,"blur",U);p(w,"dragenter",B);p(w,"dragover",B);p(w,"drop",v(function(a){a.preventDefault();var b=Ja(a,!0),e=a.dataTransfer.files;if(b&&!l.readOnly)if(e&&e.length&&window.FileReader&&window.File)for(var g=function(a,c){var d=new FileReader;d.onload=function(){f[c]=d.result;++k==h&&(b=N(b),v(function(){var a=ha(f.join(""),b,b);wa(b,
a)})())};d.readAsText(a)},h=e.length,f=Array(h),k=0,a=0;a<h;++a)g(e[a],a);else try{if(f=a.dataTransfer.getData("Text"))g=ha(f,b,b),e=c,a=d,wa(b,g),Gb&&ha("",e,a),Ca()}catch(i){}}));p(w,"paste",function(){Ca();Ra()});p(F,"paste",Ra);p(F,"cut",v(function(){Qa("")}));var jc;try{jc=Da.activeElement==F}catch(vc){}jc?setTimeout(C,20):U();var I=J.CodeMirror={getValue:function(){var a=[];q.iter(0,q.size,function(b){a.push(b.text)});return a.join("\n")},setValue:v(t),getSelection:cb,replaceSelection:v(Qa),
focus:function(){Ca();C();Ra()},setOption:function(a,b){var c=l[a];l[a]=b;"mode"==a||"indentUnit"==a?Vb():"readOnly"==a&&b?(U(),F.blur()):"theme"==a?Xb():"lineWrapping"==a&&c!=b?v(rc)():"tabSize"==a&&v(sc)();("lineNumbers"==a||"gutter"==a||"firstLineNumber"==a||"theme"==a)&&v(qc)()},getOption:function(a){return l[a]},undo:v(function(){Lb(da.done,da.undone)}),redo:v(function(){Lb(da.undone,da.done)}),indentLine:v(function(a,b){g(a)&&jb(a,null==b?"smart":b?"add":"subtract")}),indentSelection:v(function(a){if(s(c,
d))return jb(c.line,a);for(var b=d.line-(d.ch?0:1),e=c.line;e<=b;++e)jb(e,a)}),historySize:function(){return{undo:da.done.length,redo:da.undone.length}},clearHistory:function(){da=new ja},matchBrackets:v(function(){gc(!0)}),getTokenAt:v(function(a){a=N(a);return h(a.line).getTokenAt(L,kb(a.line),a.ch)}),getStateAfter:function(a){a=ib(null==a?q.size-1:a);return kb(a+1)},cursorCoords:function(a){null==a&&(a=e);return bc(a?c:d)},charCoords:function(a){return bc(N(a))},coordsChar:function(a){var b=A(G);
return Bb(a.x-b.left,a.y-b.top)},markText:v(Ab),setBookmark:function(a){var a=N(a),b=new P(a.ch);h(a.line).addMark(b);return b},setMarker:v(function(a,b,c){"number"==typeof a&&(a=h(ib(a)));a.gutterMarker={text:b,style:c};fa=!0;return a}),clearMarker:v(function(a){"number"==typeof a&&(a=h(ib(a)));a.gutterMarker=null;fa=!0}),setLineClass:v(function(a,b){return Yb(a,function(a){if(a.className!=b)return a.className=b,!0})}),hideLine:v(function(a){return Zb(a,!0)}),showLine:v(function(a){return Zb(a,!1)}),
onDeleteLine:function(a,b){if("number"==typeof a){if(!g(a))return null;a=h(a)}(a.handlers||(a.handlers=[])).push(b);return a},lineInfo:function(a){if("number"==typeof a){if(!g(a))return null;var b=a,a=h(a);if(!a)return null}else if(b=X(a),null==b)return null;var c=a.gutterMarker;return{line:b,handle:a,text:a.text,markerText:c&&c.text,markerClass:c&&c.style,lineClass:a.className}},addWidget:function(a,b,c,d,e){var a=Sa(N(a)),g=a.yBot,h=a.x;b.style.position="absolute";$.appendChild(b);if("over"==d)g=
a.y;else if("near"==d){var d=Math.max(w.offsetHeight,q.height*na()),f=Math.max($.clientWidth,G.clientWidth)-G.offsetLeft;a.yBot+b.offsetHeight>d&&a.y>b.offsetHeight&&(g=a.y-b.offsetHeight);h+b.offsetWidth>f&&(h=f-b.offsetWidth)}b.style.top=g+G.offsetTop+"px";b.style.left=b.style.right="";"right"==e?(h=$.clientWidth-b.offsetWidth,b.style.right="0px"):("left"==e?h=0:"middle"==e&&(h=($.clientWidth-b.offsetWidth)/2),b.style.left=h+G.offsetLeft+"px");c&&Pb(h,g,h+b.offsetWidth,g+b.offsetHeight)},lineCount:function(){return q.size},
clipPos:N,getCursor:function(a){null==a&&(a=e);return{line:(a?c:d).line,ch:(a?c:d).ch}},somethingSelected:function(){return!s(c,d)},setCursor:v(function(a,b,c){null==b&&"number"==typeof a.line?ya(a.line,a.ch,c):ya(a,b,c)}),setSelection:v(function(a,b,c){(c?wa:Pa)(N(a),N(b||a))}),getLine:function(a){if(g(a))return h(a).text},getLineHandle:function(a){if(g(a))return h(a)},setLine:v(function(a,b){g(a)&&ha(b,{line:a,ch:0},{line:a,ch:h(a).text.length})}),removeLine:v(function(a){g(a)&&ha("",{line:a,ch:0},
N({line:a+1,ch:0}))}),replaceRange:v(ha),getRange:function(a,b){return Nb(N(a),N(b))},execCommand:function(a){return Ba[a](I)},moveH:v(function(a,b){var e=0>a?c:d;if(Y||s(c,d))e=yb(a,b);ya(e.line,e.ch,!0)}),deleteH:v(function(a,b){s(c,d)?0>a?ha("",yb(a,b),d):ha("",c,yb(a,b)):ha("",c,d);fb=!0}),moveV:v(function(a,b){var g=0,h=Sa(e?c:d,!0);if(null!=gb)h.x=gb;"page"==b?g=w.clientHeight:"line"==b&&(g=na());g=Bb(h.x,h.y+g*a+2);ya(g.line,g.ch,!0);gb=h.x}),toggleOverwrite:function(){vb=!vb},posFromIndex:function(a){var b=
0,c;q.iter(0,q.size,function(d){d=d.text.length+1;if(d>a)return c=a,!0;a-=d;++b});return N({line:b,ch:c})},indexFromPos:function(a){if(0>a.line||0>a.ch)return 0;var b=a.ch;q.iter(0,a.line,function(a){b+=a.text.length+1});return b},operation:function(a){return v(a)()},refresh:function(){Ta(!0)},getInputField:function(){return F},getWrapperElement:function(){return J},getScrollerElement:function(){return w},getGutterElement:function(){return W}},Hb=null,rb=!1,ua="",gb=null;zb.prototype.clear=v(function(){for(var a=
Infinity,b=-Infinity,c=0,d=this.set.length;c<d;++c){var e=this.set[c],g=e.marked;if(g&&e.parent){e=X(e);a=Math.min(a,e);b=Math.max(b,e);for(e=0;e<g.length;++e)g[e].set==this.set&&g.splice(e--,1)}}Infinity!=a&&Q.push({from:a,to:b+1})});zb.prototype.find=function(){for(var a,b,c=0,d=this.set.length;c<d;++c)for(var e=this.set[c],g=e.marked,h=0;h<g.length;++h){var f=g[h];if(f.set==this.set&&(null!=f.from||null!=f.to)){var k=X(e);null!=k&&(null!=f.from&&(a={line:k,ch:f.from}),null!=f.to&&(b={line:k,ch:f.to}))}}return{from:a,
to:b}};var ac=Math.floor(16777215*Math.random()).toString(16),Cb,cc,Ea,ec,dc=0,Db={"(":")>",")":"(<","[":"]>","]":"[<","{":"}>","}":"{<"},ic=0,ab;for(ab in Ga)Ga.propertyIsEnumerable(ab)&&!I.propertyIsEnumerable(ab)&&(I[ab]=Ga[ab]);return I}function y(a,b,c){function d(a,b,c){var f=b[a];if(null!=f)return f;if(null==c)c=b.fallthrough;if(null==c)return b.catchall;if("string"==typeof c)return d(a,V[c]);for(var b=0,k=c.length;b<k;++b)if(f=d(a,V[c[b]]),null!=f)return f;return null}return b?d(a,b,c):d(a,
V[c])}function u(a,b){if(!0===b)return b;if(a.copyState)return a.copyState(b);var c={},d;for(d in b){var e=b[d];e instanceof Array&&(e=e.concat([]));c[d]=e}return c}function M(a,b,c){return a.startState?a.startState(b,c):!0}function C(a,b){this.pos=this.start=0;this.string=a;this.tabSize=b||8}function D(a,b,c,d){this.from=a;this.to=b;this.style=c;this.set=d}function P(a){this.to=this.from=a;this.line=null}function r(a,b){this.styles=b||[a,null];this.text=a;this.height=1;this.stateAfter=this.parent=
this.hidden=this.marked=this.gutterMarker=this.className=this.handlers=null}function i(a,b,c,d){for(var e=0,g=0,h=0;g<b;e+=2){var f=c[e],k=g+f.length;0==h?(k>a&&d.push(f.slice(a-g,Math.min(f.length,b-g)),c[e+1]),k>=a&&(h=1)):1==h&&(k>b?d.push(f.slice(0,b-g),c[e+1]):d.push(f,c[e+1]));g=k}}function f(a){this.lines=a;this.parent=null;for(var b=0,c=a.length,d=0;b<c;++b)a[b].parent=this,d+=a[b].height;this.height=d}function m(a){this.children=a;for(var b=0,c=0,d=0,e=a.length;d<e;++d){var g=a[d],b=b+g.chunkSize(),
c=c+g.height;g.parent=this}this.size=b;this.height=c;this.parent=null}function X(a){if(null==a.parent)return null;for(var b=a.parent,a=oa(b.lines,a),c=b.parent;c;b=c,c=c.parent)for(var d=0;!(c.children[d]==b);++d)a+=c.children[d].chunkSize();return a}function O(a,b){var c=0;a:do{for(var d=0,e=a.children.length;d<e;++d){var g=a.children[d],h=g.height;if(b<h){a=g;continue a}b-=h;c+=g.chunkSize()}return c}while(!a.lines);d=0;for(e=a.lines.length;d<e;++d){g=a.lines[d].height;if(b<g)break;b-=g}return c+
d}function j(a,b){var c=0;a:do{for(var d=0,e=a.children.length;d<e;++d){var g=a.children[d],h=g.chunkSize();if(b<h){a=g;continue a}b-=h;c+=g.height}return c}while(!a.lines);for(d=0;d<b;++d)c+=a.lines[d].height;return c}function ja(){this.time=0;this.done=[];this.undone=[]}function pa(){B(this)}function ka(a){if(!a.stop)a.stop=pa;return a}function x(a){a.preventDefault?a.preventDefault():a.returnValue=!1}function z(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}function B(a){x(a);z(a)}
function E(a){if(a.which)return a.which;if(a.button&1)return 1;if(a.button&2)return 3;if(a.button&4)return 2}function p(a,b,c,d){if("function"==typeof a.addEventListener){if(a.addEventListener(b,c,!1),d)return function(){a.removeEventListener(b,c,!1)}}else{var e=function(a){c(a||window.event)};a.attachEvent("on"+b,e);if(d)return function(){a.detachEvent("on"+b,e)}}}function k(){this.id=null}function t(a,b,c){if(null==b&&(b=a.search(/[^\s\u00a0]/),-1==b))b=a.length;for(var d=0,e=0;d<b;++d)"\t"==a.charAt(d)?
e+=c-e%c:++e;return e}function A(a,b){for(var c=a.ownerDocument.body,d=0,e=0,g=!1,h=a;h;h=h.offsetParent){var f=h.offsetLeft,k=h.offsetTop;h==c?(d+=Math.abs(f),e+=Math.abs(k)):(d+=f,e+=k);b&&"fixed"==(h.currentStyle?h.currentStyle:window.getComputedStyle(h,null)).position&&(g=!0)}c=b&&!g?null:c;for(h=a.parentNode;h!=c;h=h.parentNode)null!=h.scrollLeft&&(d-=h.scrollLeft,e-=h.scrollTop);return{left:d,top:e}}function s(a,b){return a.line==b.line&&a.ch==b.ch}function ea(a,b){return a.line<b.line||a.line==
b.line&&a.ch<b.ch}function T(a){S.textContent=a;return S.innerHTML}function Ma(a,b){if(!b)return a?a.length:0;if(!a)return b.length;for(var c=a.length,d=b.length;0<=c&&0<=d&&!(a.charAt(c)!=b.charAt(d));--c,--d);return d+1}function oa(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0,d=a.length;c<d;++c)if(a[c]==b)return c;return-1}function Ia(a){return/\w/.test(a)||a.toUpperCase()!=a.toLowerCase()}o.defaults={value:"",mode:null,theme:"default",indentUnit:2,indentWithTabs:!1,tabSize:4,keyMap:"default",
extraKeys:null,electricChars:!0,onKeyEvent:null,lineWrapping:!1,lineNumbers:!1,gutter:!1,fixedGutter:!1,firstLineNumber:1,readOnly:!1,onChange:null,onCursorActivity:null,onGutterClick:null,onHighlightComplete:null,onUpdate:null,onFocus:null,onBlur:null,onScroll:null,matchBrackets:!1,workTime:100,workDelay:200,pollInterval:100,undoDepth:40,tabindex:null,document:window.document};var $a=/Mac/.test(navigator.platform);/Win/.test(navigator.platform);var la={},U={};o.defineMode=function(a,b){if(!o.defaults.mode&&
"null"!=a)o.defaults.mode=a;la[a]=b};o.defineMIME=function(a,b){U[a]=b};o.getMode=function(a,b){"string"==typeof b&&U.hasOwnProperty(b)&&(b=U[b]);if("string"==typeof b)var c=b,d={};else if(null!=b)c=b.name,d=b;var e=la[c];return!e?(window.console&&console.warn("No mode "+c+" found, falling back to plain text."),o.getMode(a,"text/plain")):e(a,d||{})};o.listModes=function(){var a=[],b;for(b in la)la.propertyIsEnumerable(b)&&a.push(b);return a};o.listMIMEs=function(){var a=[],b;for(b in U)U.propertyIsEnumerable(b)&&
a.push({mime:b,mode:U[b]});return a};var Ga=o.extensions={};o.defineExtension=function(a,b){Ga[a]=b};var Ba=o.commands={selectAll:function(a){a.setSelection({line:0,ch:0},{line:a.lineCount()-1})},killLine:function(a){var b=a.getCursor(!0),c=a.getCursor(!1),d=!s(b,c);!d&&a.getLine(b.line).length==b.ch?a.replaceRange("",b,{line:b.line+1,ch:0}):a.replaceRange("",b,d?c:{line:b.line})},deleteLine:function(a){var b=a.getCursor().line;a.replaceRange("",{line:b,ch:0},{line:b})},undo:function(a){a.undo()},
redo:function(a){a.redo()},goDocStart:function(a){a.setCursor(0,0,!0)},goDocEnd:function(a){a.setSelection({line:a.lineCount()-1},null,!0)},goLineStart:function(a){a.setCursor(a.getCursor().line,0,!0)},goLineStartSmart:function(a){var b=a.getCursor(),c=a.getLine(b.line),c=Math.max(0,c.search(/\S/));a.setCursor(b.line,b.ch<=c&&b.ch?0:c,!0)},goLineEnd:function(a){a.setSelection({line:a.getCursor().line},null,!0)},goLineUp:function(a){a.moveV(-1,"line")},goLineDown:function(a){a.moveV(1,"line")},goPageUp:function(a){a.moveV(-1,
"page")},goPageDown:function(a){a.moveV(1,"page")},goCharLeft:function(a){a.moveH(-1,"char")},goCharRight:function(a){a.moveH(1,"char")},goColumnLeft:function(a){a.moveH(-1,"column")},goColumnRight:function(a){a.moveH(1,"column")},goWordLeft:function(a){a.moveH(-1,"word")},goWordRight:function(a){a.moveH(1,"word")},delCharLeft:function(a){a.deleteH(-1,"char")},delCharRight:function(a){a.deleteH(1,"char")},delWordLeft:function(a){a.deleteH(-1,"word")},delWordRight:function(a){a.deleteH(1,"word")},
indentAuto:function(a){a.indentSelection("smart")},indentMore:function(a){a.indentSelection("add")},indentLess:function(a){a.indentSelection("subtract")},insertTab:function(a){a.replaceSelection("\t","end")},transposeChars:function(a){var b=a.getCursor(),c=a.getLine(b.line);0<b.ch&&b.ch<c.length-1&&a.replaceRange(c.charAt(b.ch)+c.charAt(b.ch-1),{line:b.line,ch:b.ch-1},{line:b.line,ch:b.ch+1})},newlineAndIndent:function(a){a.replaceSelection("\n","end");a.indentLine(a.getCursor().line)},toggleOverwrite:function(a){a.toggleOverwrite()}},
V=o.keyMap={};V.basic={Left:"goCharLeft",Right:"goCharRight",Up:"goLineUp",Down:"goLineDown",End:"goLineEnd",Home:"goLineStartSmart",PageUp:"goPageUp",PageDown:"goPageDown",Delete:"delCharRight",Backspace:"delCharLeft",Tab:"indentMore","Shift-Tab":"indentLess",Enter:"newlineAndIndent",Insert:"toggleOverwrite"};V.pcDefault={"Ctrl-A":"selectAll","Ctrl-D":"deleteLine","Ctrl-Z":"undo","Shift-Ctrl-Z":"redo","Ctrl-Y":"redo","Ctrl-Home":"goDocStart","Alt-Up":"goDocStart","Ctrl-End":"goDocEnd","Ctrl-Down":"goDocEnd",
"Ctrl-Left":"goWordLeft","Ctrl-Right":"goWordRight","Alt-Left":"goLineStart","Alt-Right":"goLineEnd","Ctrl-Backspace":"delWordLeft","Ctrl-Delete":"delWordRight","Ctrl-S":"save","Ctrl-F":"find","Ctrl-G":"findNext","Shift-Ctrl-G":"findPrev","Shift-Ctrl-F":"replace","Shift-Ctrl-R":"replaceAll",fallthrough:"basic"};V.macDefault={"Cmd-A":"selectAll","Cmd-D":"deleteLine","Cmd-Z":"undo","Shift-Cmd-Z":"redo","Cmd-Y":"redo","Cmd-Up":"goDocStart","Cmd-End":"goDocEnd","Cmd-Down":"goDocEnd","Alt-Left":"goWordLeft",
"Alt-Right":"goWordRight","Cmd-Left":"goLineStart","Cmd-Right":"goLineEnd","Alt-Backspace":"delWordLeft","Ctrl-Alt-Backspace":"delWordRight","Alt-Delete":"delWordRight","Cmd-S":"save","Cmd-F":"find","Cmd-G":"findNext","Shift-Cmd-G":"findPrev","Cmd-Alt-F":"replace","Shift-Cmd-Alt-F":"replaceAll",fallthrough:["basic","emacsy"]};V["default"]=$a?V.macDefault:V.pcDefault;V.emacsy={"Ctrl-F":"goCharRight","Ctrl-B":"goCharLeft","Ctrl-P":"goLineUp","Ctrl-N":"goLineDown","Alt-F":"goWordRight","Alt-B":"goWordLeft",
"Ctrl-A":"goLineStart","Ctrl-E":"goLineEnd","Ctrl-V":"goPageUp","Shift-Ctrl-V":"goPageDown","Ctrl-D":"delCharRight","Ctrl-H":"delCharLeft","Alt-D":"delWordRight","Alt-Backspace":"delWordLeft","Ctrl-K":"killLine","Ctrl-T":"transposeChars"};o.fromTextArea=function(a,b){function c(){a.value=h.getValue()}b||(b={});b.value=a.value;if(!b.tabindex&&a.tabindex)b.tabindex=a.tabindex;if(a.form){var d=p(a.form,"submit",c,!0);if("function"==typeof a.form.submit){var e=a.form.submit,g=function(){c();a.form.submit=
e;a.form.submit();a.form.submit=g};a.form.submit=g}}a.style.display="none";var h=o(function(b){a.parentNode.insertBefore(b,a.nextSibling)},b);h.save=c;h.getTextArea=function(){return a};h.toTextArea=function(){c();a.parentNode.removeChild(h.getWrapperElement());a.style.display="";if(a.form&&(d(),"function"==typeof a.form.submit))a.form.submit=e};return h};o.copyState=u;o.startState=M;C.prototype={eol:function(){return this.pos>=this.string.length},sol:function(){return 0==this.pos},peek:function(){return this.string.charAt(this.pos)},
next:function(){if(this.pos<this.string.length)return this.string.charAt(this.pos++)},eat:function(a){var b=this.string.charAt(this.pos);if("string"==typeof a?b==a:b&&(a.test?a.test(b):a(b)))return++this.pos,b},eatWhile:function(a){for(var b=this.pos;this.eat(a););return this.pos>b},eatSpace:function(){for(var a=this.pos;/[\s\u00a0]/.test(this.string.charAt(this.pos));)++this.pos;return this.pos>a},skipToEnd:function(){this.pos=this.string.length},skipTo:function(a){a=this.string.indexOf(a,this.pos);
if(-1<a)return this.pos=a,!0},backUp:function(a){this.pos-=a},column:function(){return t(this.string,this.start,this.tabSize)},indentation:function(){return t(this.string,null,this.tabSize)},match:function(a,b,c){if("string"==typeof a){if((c?this.string.toLowerCase():this.string).indexOf(c?a.toLowerCase():a,this.pos)==this.pos)return!1!==b&&(this.pos+=a.length),!0}else{if((a=this.string.slice(this.pos).match(a))&&!1!==b)this.pos+=a[0].length;return a}},current:function(){return this.string.slice(this.start,
this.pos)}};o.StringStream=C;D.prototype={attach:function(a){this.set.push(a)},detach:function(a){a=oa(this.set,a);-1<a&&this.set.splice(a,1)},split:function(a,b){return this.to<=a&&null!=this.to?null:new D(this.from<a||null==this.from?null:this.from-a+b,null==this.to?null:this.to-a+b,this.style,this.set)},dup:function(){return new D(null,null,this.style,this.set)},clipTo:function(a,b,c,d,e){if(null!=this.from&&this.from>=b)this.from=Math.max(d,this.from)+e;if(null!=this.to&&this.to>b)this.to=d<this.to?
this.to+e:b;if(a&&d>this.from&&(d<this.to||null==this.to))this.from=null;if(c&&(b<this.to||null==this.to)&&(b>this.from||null==this.from))this.to=null},isDead:function(){return null!=this.from&&null!=this.to&&this.from>=this.to},sameSet:function(a){return this.set==a.set}};P.prototype={attach:function(a){this.line=a},detach:function(a){if(this.line==a)this.line=null},split:function(a,b){if(a<this.from)return this.from=this.to=this.from-a+b,this},isDead:function(){return this.from>this.to},clipTo:function(a,
b,c,d,e){if((a||b<this.from)&&(c||d>this.to))this.from=0,this.to=-1;else if(this.from>b)this.from=this.to=Math.max(d,this.from)+e},sameSet:function(){return!1},find:function(){return!this.line||!this.line.parent?null:{line:X(this.line),ch:this.from}},clear:function(){if(this.line){var a=oa(this.line.marked,this);-1!=a&&this.line.marked.splice(a,1);this.line=null}}};r.inheritMarks=function(a,b){var c=new r(a),d=b&&b.marked;if(d)for(var e=0;e<d.length;++e)if(null==d[e].to&&d[e].style){var g=c.marked||
(c.marked=[]),h=d[e].dup();g.push(h);h.attach(c)}return c};r.prototype={replace:function(a,b,c){var d=[],e=this.marked,g=null==b?this.text.length:b;i(0,a,this.styles,d);c&&d.push(c,null);i(g,this.text.length,this.styles,d);this.styles=d;this.text=this.text.slice(0,a)+c+this.text.slice(g);this.stateAfter=null;if(e)for(var c=c.length-(g-a),d=0,h=e[d];d<e.length;++d)h.clipTo(null==a,a||0,null==b,g,c),h.isDead()&&(h.detach(this),e.splice(d--,1))},split:function(a,b){var c=[b,null],d=this.marked;i(a,this.text.length,
this.styles,c);c=new r(b+this.text.slice(a),c);if(d)for(var e=0;e<d.length;++e){var g=d[e].split(a,b.length);if(g){if(!c.marked)c.marked=[];c.marked.push(g);g.attach(c)}}return c},append:function(a){var b=this.text.length,c=a.marked,d=this.marked;this.text+=a.text;i(0,a.text.length,a.styles,this.styles);if(d)for(a=0;a<d.length;++a)if(null==d[a].to)d[a].to=b;if(c&&c.length){if(!d)this.marked=d=[];a=0;a:for(;a<c.length;++a){var e=c[a];if(!e.from)for(var g=0;g<d.length;++g){var h=d[g];if(h.to==b&&h.sameSet(e)){h.to=
null==e.to?null:e.to+b;h.isDead()&&(h.detach(this),c.splice(a--,1));continue a}}d.push(e);e.attach(this);e.from+=b;null!=e.to&&(e.to+=b)}}},fixMarkEnds:function(a){var b=this.marked,a=a.marked;if(b)for(var c=0;c<b.length;++c){var d=b[c],e=null==d.to;if(e&&a)for(var g=0;g<a.length;++g)if(a[g].sameSet(d)){e=!1;break}if(e)d.to=this.text.length}},fixMarkStarts:function(){var a=this.marked;if(a)for(var b=0;b<a.length;++b)if(null==a[b].from)a[b].from=0},addMark:function(a){a.attach(this);if(null==this.marked)this.marked=
[];this.marked.push(a);this.marked.sort(function(a,c){return(a.from||0)-(c.from||0)})},highlight:function(a,b,c){var c=new C(this.text,c),d=this.styles,e=0,g=!1,h=d[0],f;for(""==this.text&&a.blankLine&&a.blankLine(b);!c.eol();){var k=a.token(c,b),i=this.text.slice(c.start,c.pos);c.start=c.pos;if(e&&d[e-1]==k)d[e-2]+=i;else if(i){if(!g&&(d[e+1]!=k||e&&d[e-2]!=f))g=!0;d[e++]=i;d[e++]=k;f=h;h=d[e]}if(5E3<c.pos){d[e++]=this.text.slice(c.pos);d[e++]=null;break}}if(d.length!=e)d.length=e,g=!0;e&&d[e-2]!=
f&&(g=!0);return g||(5>d.length&&10>this.text.length?null:!1)},getTokenAt:function(a,b,c){for(var d=new C(this.text);d.pos<c&&!d.eol();){d.start=d.pos;var e=a.token(d,b)}return{start:d.start,end:d.pos,string:d.current(),className:e||null,state:b}},indentation:function(a){return t(this.text,null,a)},getHTML:function(a,b,c,d,e){function g(a,b){a&&(f&&va&&" "==a.charAt(0)&&(a="\u00a0"+a.slice(1)),f=!1,b?h.push('<span class="',b,'">',T(a).replace(/\t/g,d),"</span>"):h.push(T(a).replace(/\t/g,d)))}var h=
[],f=!0;c&&h.push(this.className?'<pre class="'+this.className+'">':"<pre>");var k=this.styles,i=this.text,t=this.marked;a==b&&(a=null);var j=i.length;null!=e&&(j=Math.min(e,j));if(!i&&null==e)g(" ",null!=a&&null==b?"CodeMirror-selected":null);else if(!t&&null==a)for(a=e=0;a<j;e+=2){var b=k[e],s=k[e+1],i=b.length;a+i>j&&(b=b.slice(0,j-a));a+=i;g(b,s&&"cm-"+s)}else{var e=i=0,m="",p=-1,A=null,r=function(){t&&(p+=1,A=p<t.length?t[p]:null)};for(r();i<j;){var o=j,u="";if(null!=a)if(a>i)o=a;else if(null==
b||b>i)u=" CodeMirror-selected",null!=b&&(o=Math.min(o,b));for(;A&&null!=A.to&&A.to<=i;)r();A&&(A.from>i?o=Math.min(o,A.from):(u+=" "+A.style,null!=A.to&&(o=Math.min(o,A.to))));for(;;){var X=i+m.length,x=s;u&&(x=s?s+u:u);g(X>o?m.slice(0,o-i):m,x);if(X>=o){m=m.slice(o-i);i=o;break}i=X;m=k[e++];s="cm-"+k[e++]}}null!=a&&null==b&&g(" ","CodeMirror-selected")}c&&h.push("</pre>");return h.join("")},cleanUp:function(){this.parent=null;if(this.marked)for(var a=0,b=this.marked.length;a<b;++a)this.marked[a].detach(this)}};
f.prototype={chunkSize:function(){return this.lines.length},remove:function(a,b,c){for(var d=a,e=a+b;d<e;++d){var g=this.lines[d];this.height-=g.height;g.cleanUp();if(g.handlers)for(var h=0;h<g.handlers.length;++h)c.push(g.handlers[h])}this.lines.splice(a,b)},collapse:function(a){a.splice.apply(a,[a.length,0].concat(this.lines))},insertHeight:function(a,b,c){this.height+=c;this.lines.splice.apply(this.lines,[a,0].concat(b));a=0;for(c=b.length;a<c;++a)b[a].parent=this},iterN:function(a,b,c){for(b=
a+b;a<b;++a)if(c(this.lines[a]))return!0}};m.prototype={chunkSize:function(){return this.size},remove:function(a,b,c){this.size-=b;for(var d=0;d<this.children.length;++d){var e=this.children[d],g=e.chunkSize();if(a<g){var h=Math.min(b,g-a),k=e.height;e.remove(a,h,c);this.height-=k-e.height;if(g==h)this.children.splice(d--,1),e.parent=null;if(0==(b-=h))break;a=0}else a-=g}if(25>this.size-b)a=[],this.collapse(a),this.children=[new f(a)]},collapse:function(a){for(var b=0,c=this.children.length;b<c;++b)this.children[b].collapse(a)},
insert:function(a,b){for(var c=0,d=0,e=b.length;d<e;++d)c+=b[d].height;this.insertHeight(a,b,c)},insertHeight:function(a,b,c){this.size+=b.length;this.height+=c;for(var d=0,e=this.children.length;d<e;++d){var g=this.children[d],h=g.chunkSize();if(a<=h){g.insertHeight(a,b,c);if(g.lines&&50<g.lines.length){for(;50<g.lines.length;)a=g.lines.splice(g.lines.length-25,25),a=new f(a),g.height-=a.height,this.children.splice(d+1,0,a),a.parent=this;this.maybeSpill()}break}a-=h}},maybeSpill:function(){if(!(10>=
this.children.length)){var a=this;do{var b=a.children.splice(a.children.length-5,5),b=new m(b);if(a.parent){a.size-=b.size;a.height-=b.height;var c=oa(a.parent.children,a);a.parent.children.splice(c+1,0,b)}else c=new m(a.children),c.parent=a,a.children=[c,b],a=c;b.parent=a.parent}while(10<a.children.length);a.parent.maybeSpill()}},iter:function(a,b,c){this.iterN(a,b-a,c)},iterN:function(a,b,c){for(var d=0,e=this.children.length;d<e;++d){var g=this.children[d],h=g.chunkSize();if(a<h){h=Math.min(b,
h-a);if(g.iterN(a,h,c))return!0;if(0==(b-=h))break;a=0}else a-=h}}};ja.prototype={addChange:function(a,b,c){this.undone.length=0;var d=+new Date,e=this.done[this.done.length-1];if(400<d-this.time||!e||e.start>a+b||e.start+e.added<a-e.added+e.old.length)this.done.push({start:a,added:b,old:c});else{var g=0;if(a<e.start){for(var h=e.start-a-1;0<=h;--h)e.old.unshift(c[h]);e.added+=e.start-a;e.start=a}else e.start<a&&(g=a-e.start,b+=g);h=e.added-g;for(a=c.length;h<a;++h)e.old.push(c[h]);if(e.added<b)e.added=
b}this.time=d}};o.e_stop=B;o.e_preventDefault=x;o.e_stopPropagation=z;o.connect=p;k.prototype={set:function(a,b){clearTimeout(this.id);this.id=setTimeout(b,a)}};var Aa;Aa=/MSIE [1-8]\b/.test(navigator.userAgent)?!1:"draggable"in document.createElement("div");var Xa=/gecko\/\d{7}/i.test(navigator.userAgent),va=/MSIE \d/.test(navigator.userAgent),Fa=/WebKit\//.test(navigator.userAgent);(function(){var a=document.createElement("textarea");a.value="foo\nbar";a.value.indexOf("\r")})();null!=document.documentElement.getBoundingClientRect&&
(A=function(a,b){try{var c=a.getBoundingClientRect(),c={top:c.top,left:c.left}}catch(d){c={top:0,left:0}}if(!b)if(null==window.pageYOffset){var e=document.documentElement||document.body.parentNode;if(null==e.scrollTop)e=document.body;c.top+=e.scrollTop;c.left+=e.scrollLeft}else c.top+=window.pageYOffset,c.left+=window.pageXOffset;return c});var S=document.createElement("pre");"\na"==T("a")?T=function(a){S.textContent=a;return S.innerHTML.slice(1)}:"\t"!=T("\t")&&(T=function(a){S.innerHTML="";S.appendChild(document.createTextNode(a));
return S.innerHTML});o.htmlEscape=T;var qa=3!="\n\nb".split(/\n/).length?function(a){for(var b=0,c,d=[];-1<(c=a.indexOf("\n",b));)d.push(a.slice(b,"\r"==a.charAt(c-1)?c-1:c)),b=c+1;d.push(a.slice(b));return d}:function(a){return a.split(/\r?\n/)};o.splitLines=qa;var db=window.getSelection?function(a){try{return a.selectionStart!=a.selectionEnd}catch(b){return!1}}:function(a){try{var b=a.ownerDocument.selection.createRange()}catch(c){}return!b||b.parentElement()!=a?!1:0!=b.compareEndPoints("StartToEnd",
b)};o.defineMode("null",function(){return{token:function(a){a.skipToEnd()}}});o.defineMIME("text/plain","null");var ma={3:"Enter",8:"Backspace",9:"Tab",13:"Enter",16:"Shift",17:"Ctrl",18:"Alt",19:"Pause",20:"CapsLock",27:"Esc",32:"Space",33:"PageUp",34:"PageDown",35:"End",36:"Home",37:"Left",38:"Up",39:"Right",40:"Down",44:"PrintScrn",45:"Insert",46:"Delete",59:";",91:"Mod",92:"Mod",93:"Mod",186:";",187:"=",188:",",189:"-",190:".",191:"/",192:"`",219:"[",220:"\\",221:"]",222:"'",63276:"PageUp",63277:"PageDown",
63275:"End",63273:"Home",63234:"Left",63232:"Up",63235:"Right",63233:"Down",63302:"Insert",63272:"Delete"};o.keyNames=ma;(function(){for(var a=0;10>a;a++)ma[a+48]=""+a;for(a=65;90>=a;a++)ma[a]=String.fromCharCode(a);for(a=1;12>=a;a++)ma[a+111]=ma[a+63235]="F"+a})();return o}();
CodeMirror.defineMode("xml",function(o,y){function u(f,i){function j(s){i.tokenize=s;return s(f,i)}var s=f.next();if("<"==s){if(f.eat("!")){if(f.eat("["))return f.match("CDATA[")?j(D("atom","]]\>")):null;if(f.match("--"))return j(D("comment","--\>"));return f.match("DOCTYPE",!0,!0)?(f.eatWhile(/[\w\._\-]/),j(P(1))):null}if(f.eat("?"))return f.eatWhile(/[\w\._\-]/),i.tokenize=D("meta","?>"),"meta";B=f.eat("/")?"closeTag":"openTag";f.eatSpace();for(z="";s=f.eat(/[^\s\u00a0=<>\"\'\/?]/);)z+=s;i.tokenize=
M;return"tag"}if("&"==s)return f.eatWhile(/[^;]/),f.eat(";"),"atom";f.eatWhile(/[^&<]/);return null}function M(f,i){var j=f.next();if(">"==j||"/"==j&&f.eat(">"))return i.tokenize=u,B=">"==j?"endTag":"selfcloseTag","tag";if("="==j)return B="equals",null;if(/[\'\"]/.test(j))return i.tokenize=C(j),i.tokenize(f,i);f.eatWhile(/[^\s\u00a0=<>\"\'\/?]/);return"word"}function C(f){return function(i,j){for(;!i.eol();)if(i.next()==f){j.tokenize=M;break}return"string"}}function D(f,i){return function(j,s){for(;!j.eol();){if(j.match(i)){s.tokenize=
u;break}j.next()}return f}}function P(f){return function(i,j){for(var s;null!=(s=i.next());){if("<"==s)return j.tokenize=P(f+1),j.tokenize(i,j);if(">"==s)if(1==f){j.tokenize=u;break}else return j.tokenize=P(f-1),j.tokenize(i,j)}return"meta"}}function r(){for(var f=arguments.length-1;0<=f;f--)E.cc.push(arguments[f])}function i(){r.apply(null,arguments);return!0}function f(f){if("openTag"==f)return E.tagName=z,i(O,m(E.startOfLine));return"closeTag"==f?(f=!1,(f=E.context?E.context.tagName!=z:!0)&&(p=
"error"),i(X(f))):i()}function m(f){return function(j){if("selfcloseTag"==j||"endTag"==j&&ka.autoSelfClosers.hasOwnProperty(E.tagName.toLowerCase()))return i();if("endTag"==j){var j=E.tagName,m=ka.doNotIndent.hasOwnProperty(j)||E.context&&E.context.noIndent;E.context={prev:E.context,tagName:j,indent:E.indented,startOfLine:f,noIndent:m}}return i()}}function X(f){return function(j){f&&(p="error");if("endTag"==j){if(E.context)E.context=E.context.prev;return i()}p="error";return i(arguments.callee)}}
function O(f){if("word"==f)return p="attribute",i(O);if("equals"==f)return i(j,O);return"string"==f?(p="error",i(O)):r()}function j(f){return"word"==f&&ka.allowUnquoted?(p="string",i()):"string"==f?i(ja):r()}function ja(f){return"string"==f?i(ja):r()}var pa=o.indentUnit,ka=y.htmlMode?{autoSelfClosers:{br:!0,img:!0,hr:!0,link:!0,input:!0,meta:!0,col:!0,frame:!0,base:!0,area:!0},doNotIndent:{pre:!0},allowUnquoted:!0}:{autoSelfClosers:{},doNotIndent:{},allowUnquoted:!1},x=y.alignCDATA,z,B,E,p;return{startState:function(){return{tokenize:u,
cc:[],indented:0,startOfLine:!0,tagName:null,context:null}},token:function(i,j){if(i.sol())j.startOfLine=!0,j.indented=i.indentation();if(i.eatSpace())return null;p=B=z=null;var m=j.tokenize(i,j);j.type=B;if((m||B)&&"comment"!=m)for(E=j;!(j.cc.pop()||f)(B||m););j.startOfLine=!1;return p||m},indent:function(f,i,j){var m=f.context;if(f.tokenize!=M&&f.tokenize!=u||m&&m.noIndent)return j?j.match(/^(\s*)/)[0].length:0;if(x&&/<!\[CDATA\[/.test(i))return 0;if(m&&/^<\//.test(i))m=m.prev;for(;m&&!m.startOfLine;)m=
m.prev;return m?m.indent+pa:0},compareStates:function(f,i){if(f.indented!=i.indented||f.tokenize!=i.tokenize)return!1;for(var j=f.context,m=i.context;;j=j.prev,m=m.prev){if(!j||!m)return j==m;if(j.tagName!=m.tagName)return!1}},electricChars:"/"}});CodeMirror.defineMIME("application/xml","xml");CodeMirror.defineMIME("text/html",{name:"xml",htmlMode:!0});
CodeMirror.defineMode("javascript",function(o,y){var u,M,C,D;function P(a,b){for(var c=!1,d;null!=(d=a.next());){if(d==b&&!c)return!1;c=!c&&"\\"==d}return c}function r(a,b,c){S=a;qa=c;return b}function i(a,b){var c=a.next();if('"'==c||"'"==c)return c=f(c),b.tokenize=c,c(a,b);if(/[\[\]{}\(\),;\:\.]/.test(c))return r(c);if("0"==c&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),r("number","number");if(/\d/.test(c))return a.match(/^\d*(?:\.\d*)?(?:[eE][+\-]?\d+)?/),r("number","number");if("/"==c){if(a.eat("*"))return c=
m,b.tokenize=c,c(a,b);if(a.eat("/"))return a.skipToEnd(),r("comment","comment");if(b.reAllowed)return P(a,"/"),a.eatWhile(/[gimy]/),r("regexp","string");a.eatWhile(Fa);return r("operator",null,a.current())}if("#"==c)return a.skipToEnd(),r("error","error");if(Fa.test(c))return a.eatWhile(Fa),r("operator",null,a.current());a.eatWhile(/[\w\$_]/);var c=a.current(),d=va.propertyIsEnumerable(c)&&va[c];return d&&b.kwAllowed?r(d.type,d.style,c):r("variable","variable",c)}function f(a){return function(b,c){if(!P(b,
a))c.tokenize=i;return r("string","string")}}function m(a,b){for(var c=!1,d;d=a.next();){if("/"==d&&c){b.tokenize=i;break}c="*"==d}return r("comment","comment")}function X(a,b,c,d,e,f){this.indented=a;this.column=b;this.type=c;this.prev=e;this.info=f;if(null!=d)this.align=d}function O(){for(var a=arguments.length-1;0<=a;a--)D.push(arguments[a])}function j(){O.apply(null,arguments);return!0}function ja(a){var b=u;if(b.context){C="def";for(var c=b.localVars;c;c=c.next)if(c.name==a)return;b.localVars=
{name:a,next:b.localVars}}}function pa(){if(!u.context)u.localVars=ma;u.context={prev:u.context,vars:u.localVars}}function ka(){u.localVars=u.context.vars;u.context=u.context.prev}function x(a,b){var c=function(){var c=u;c.lexical=new X(c.indented,M.column(),a,null,c.lexical,b)};c.lex=!0;return c}function z(){var a=u;if(a.lexical.prev){if(")"==a.lexical.type)a.indented=a.lexical.indented;a.lexical=a.lexical.prev}}function B(a){return function(b){return b==a?j():";"==a?O():j(arguments.callee)}}function E(a){return"var"==
a?j(x("vardef"),oa,B(";"),z):"keyword a"==a?j(x("form"),p,E,z):"keyword b"==a?j(x("form"),E,z):"{"==a?j(x("}"),Ma,z):";"==a?j():"function"==a?j(Ba):"for"==a?j(x("form"),B("("),x(")"),$a,B(")"),z,E,z):"variable"==a?j(x("stat"),A):"switch"==a?j(x("form"),p,x("}","switch"),B("{"),Ma,z,z):"case"==a?j(p,B(":")):"default"==a?j(B(":")):"catch"==a?j(x("form"),pa,B("("),V,B(")"),E,z,ka):O(x("stat"),p,B(";"),z)}function p(a){return db.hasOwnProperty(a)?j(t):"function"==a?j(Ba):"keyword c"==a?j(k):"("==a?j(x(")"),
p,B(")"),z,t):"operator"==a?j(p):"["==a?j(x("]"),T(p,"]"),z,t):"{"==a?j(x("}"),T(ea,"}"),z,t):j()}function k(a){return a.match(/[;\}\)\],]/)?O():O(p)}function t(a,b){if("operator"==a&&/\+\+|--/.test(b))return j(t);if("operator"==a)return j(p);if(";"!=a){if("("==a)return j(x(")"),T(p,")"),z,t);if("."==a)return j(s,t);if("["==a)return j(x("]"),p,B("]"),z,t)}}function A(a){return":"==a?j(z,E):O(t,B(";"),z)}function s(a){if("variable"==a)return C="property",j()}function ea(a){"variable"==a&&(C="property");
if(db.hasOwnProperty(a))return j(B(":"),p)}function T(a,b){function c(d){return","==d?j(a,c):d==b?j():j(B(b))}return function(d){return d==b?j():O(a,c)}}function Ma(a){return"}"==a?j():O(E,Ma)}function oa(a,b){return"variable"==a?(ja(b),j(Ia)):j()}function Ia(a,b){if("="==b)return j(p,Ia);if(","==a)return j(oa)}function $a(a){return"var"==a?j(oa,U):";"==a?O(U):"variable"==a?j(la):O(U)}function la(a,b){return"in"==b?j(p):j(t,U)}function U(a,b){return";"==a?j(Ga):"in"==b?j(p):j(p,B(";"),Ga)}function Ga(a){")"!=
a&&j(p)}function Ba(a,b){if("variable"==a)return ja(b),j(Ba);if("("==a)return j(x(")"),pa,T(V,")"),z,E,ka)}function V(a,b){if("variable"==a)return ja(b),j()}var Aa=o.indentUnit,Xa=y.json,va=function(){function a(a){return{type:a,style:"keyword"}}var b=a("keyword a"),c=a("keyword b"),d=a("keyword c"),e=a("operator"),f={type:"atom",style:"atom"};return{"if":b,"while":b,"with":b,"else":c,"do":c,"try":c,"finally":c,"return":d,"break":d,"continue":d,"new":d,"delete":d,"throw":d,"var":a("var"),"const":a("var"),
let:a("var"),"function":a("function"),"catch":a("catch"),"for":a("for"),"switch":a("switch"),"case":a("case"),"default":a("default"),"in":e,"typeof":e,"instanceof":e,"true":f,"false":f,"null":f,undefined:f,NaN:f,Infinity:f}}(),Fa=/[+\-*&%=<>!?|]/,S,qa,db={atom:!0,number:!0,variable:!0,string:!0,regexp:!0};u=null;C=null;D=null;M=void 0;var ma={name:"this",next:{name:"arguments"}};z.lex=!0;return{startState:function(a){return{tokenize:i,reAllowed:!0,kwAllowed:!0,cc:[],lexical:new X((a||0)-Aa,0,"block",
!1),localVars:null,context:null,indented:0}},token:function(a,b){if(a.sol()){if(!b.lexical.hasOwnProperty("align"))b.lexical.align=!1;b.indented=a.indentation()}if(a.eatSpace())return null;var c=b.tokenize(a,b);if("comment"==S)return c;b.reAllowed="operator"==S||"keyword c"==S||S.match(/^[\[{}\(,;:]$/);b.kwAllowed="."!=S;var d;a:{var e=S,f=qa,h=b.cc;u=b;M=a;C=null;D=h;if(!b.lexical.hasOwnProperty("align"))b.lexical.align=!0;for(;;)if((h.length?h.pop():Xa?p:E)(e,f)){for(;h.length&&h[h.length-1].lex;)h.pop()();
if(C){d=C;break a}if(d="variable"==e)b:{for(d=b.localVars;d;d=d.next)if(d.name==f){d=!0;break b}d=void 0}d=d?"variable-2":c;break a}}return d},indent:function(a,b){if(a.tokenize!=i)return 0;var c=b&&b.charAt(0),d=a.lexical,e=d.type,f=c==e;return"vardef"==e?d.indented+4:"form"==e&&"{"==c?d.indented:"stat"==e||"form"==e?d.indented+Aa:"switch"==d.info&&!f?d.indented+(/^(?:case|default)\b/.test(b)?Aa:2*Aa):d.align?d.column+(f?0:1):d.indented+(f?0:Aa)},electricChars:":{}"}});
CodeMirror.defineMIME("text/javascript","javascript");CodeMirror.defineMIME("application/json",{name:"javascript",json:!0});
CodeMirror.defineMode("css",function(o){function y(i,f){r=f;return i}function u(i,f){var m=i.next();if("@"==m)return i.eatWhile(/[\w\\\-]/),y("meta",i.current());if("/"==m&&i.eat("*"))return f.tokenize=M,M(i,f);if("<"==m&&i.eat("!"))return f.tokenize=C,C(i,f);if("="==m)y(null,"compare");else{if(("~"==m||"|"==m)&&i.eat("="))return y(null,"compare");if('"'==m||"'"==m)return f.tokenize=D(m),f.tokenize(i,f);if("#"==m)return i.eatWhile(/[\w\\\-]/),y("atom","hash");if("!"==m)return i.match(/^\s*\w*/),y("keyword",
"important");if(/\d/.test(m))return i.eatWhile(/[\w.%]/),y("number","unit");if(/[,.+>*\/]/.test(m))return y(null,"select-op");if(/[;{}:\[\]]/.test(m))return y(null,m);i.eatWhile(/[\w\\\-]/);return y("variable","variable")}}function M(i,f){for(var m=!1,o;null!=(o=i.next());){if(m&&"/"==o){f.tokenize=u;break}m="*"==o}return y("comment","comment")}function C(i,f){for(var m=0,o;null!=(o=i.next());){if(2<=m&&">"==o){f.tokenize=u;break}m="-"==o?m+1:0}return y("comment","comment")}function D(i){return function(f,
m){for(var o=!1,r;null!=(r=f.next())&&(!(r==i)||o);)o=!o&&"\\"==r;if(!o)m.tokenize=u;return y("string","string")}}var P=o.indentUnit,r;return{startState:function(i){return{tokenize:u,baseIndent:i||0,stack:[]}},token:function(i,f){if(i.eatSpace())return null;var m=f.tokenize(i,f),o=f.stack[f.stack.length-1];if("hash"==r&&"rule"==o)m="atom";else if("variable"==m)if("rule"==o)m="number";else if(!o||"@media{"==o)m="tag";"rule"==o&&/^[\{\};]$/.test(r)&&f.stack.pop();"{"==r?"@media"==o?f.stack[f.stack.length-
1]="@media{":f.stack.push("{"):"}"==r?f.stack.pop():"@media"==r?f.stack.push("@media"):"{"==o&&"comment"!=r&&f.stack.push("rule");return m},indent:function(i,f){var m=i.stack.length;/^\}/.test(f)&&(m-="rule"==i.stack[i.stack.length-1]?2:1);return i.baseIndent+m*P},electricChars:"}"}});CodeMirror.defineMIME("text/css","css");
CodeMirror.defineMode("htmlmixed",function(o){function y(i,f){var m=D.token(i,f.htmlState);if("tag"==m&&">"==i.current()&&f.htmlState.context)if(/^script$/i.test(f.htmlState.context.tagName))f.token=M,f.localState=P.startState(D.indent(f.htmlState,"")),f.mode="javascript";else if(/^style$/i.test(f.htmlState.context.tagName))f.token=C,f.localState=r.startState(D.indent(f.htmlState,"")),f.mode="css";return m}function u(i,f,m){var o=i.current(),f=o.search(f);-1<f&&i.backUp(o.length-f);return m}function M(i,
f){return i.match(/^<\/\s*script\s*>/i,!1)?(f.token=y,f.curState=null,f.mode="html",y(i,f)):u(i,/<\/\s*script\s*>/,P.token(i,f.localState))}function C(i,f){return i.match(/^<\/\s*style\s*>/i,!1)?(f.token=y,f.localState=null,f.mode="html",y(i,f)):u(i,/<\/\s*style\s*>/,r.token(i,f.localState))}var D=CodeMirror.getMode(o,{name:"xml",htmlMode:!0}),P=CodeMirror.getMode(o,"javascript"),r=CodeMirror.getMode(o,"css");return{startState:function(){var i=D.startState();return{token:y,localState:null,mode:"html",
htmlState:i}},copyState:function(i){if(i.localState)var f=CodeMirror.copyState(i.token==C?r:P,i.localState);return{token:i.token,localState:f,mode:i.mode,htmlState:CodeMirror.copyState(D,i.htmlState)}},token:function(i,f){return f.token(i,f)},indent:function(i,f){return i.token==y||/^\s*<\//.test(f)?D.indent(i.htmlState,f):i.token==M?P.indent(i.localState,f):r.indent(i.localState,f)},compareStates:function(i,f){return D.compareStates(i.htmlState,f.htmlState)},electricChars:"/{}:"}});
CodeMirror.defineMIME("text/html","htmlmixed");
CodeMirror.runMode=function(d,e,b,g){var e=CodeMirror.getMode({indentUnit:2},e),h=1==b.nodeType;if(h)var i=b,f=[],b=function(a,b){"\n"==a?f.push("<br>"):b?f.push('<span class="cm-'+CodeMirror.htmlEscape(b)+'">'+CodeMirror.htmlEscape(a)+"</span>"):f.push(CodeMirror.htmlEscape(a))};for(var d=CodeMirror.splitLines(d),j=CodeMirror.startState(e),c=0,k=d.length;c<k;++c){c&&b("\n");for(var a=new CodeMirror.StringStream(d[c]);!a.eol();){var l=e.token(a,j);b(a.current(),l,c,a.start);a.start=a.pos}}if(h)i.innerHTML=f.join("");"function"==typeof g&&g()};