queryParameters:
  nextPageToken?:
    type: string
    description: List response may contain this parameter pointing to the next results page. All other query parameteres must be the same as for a previous request or the page token will be revalidated.
