function com_google_gwt_xhr2_XMLHttpRequest2(){var O='bootstrap',P='begin',Q='gwt.codesvr.com.google.gwt.xhr2.XMLHttpRequest2=',R='gwt.codesvr=',S='com.google.gwt.xhr2.XMLHttpRequest2',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='com_google_gwt_xhr2_XMLHttpRequest2',ob='Failed to load ',pb='head',qb='meta',rb='name',sb='com.google.gwt.xhr2.XMLHttpRequest2::',tb='::',ub='gwt:property',vb='content',wb='=',xb='gwt:onPropertyErrorFn',yb='Bad handler "',zb='" for "gwt:onPropertyErrorFn"',Ab='gwt:onLoadErrorFn',Bb='" for "gwt:onLoadErrorFn"',Cb='#',Db='?',Eb='/',Fb='img',Gb='clear.cache.gif',Hb='baseUrl',Ib='com.google.gwt.xhr2.XMLHttpRequest2.nocache.js',Jb='base',Kb='//',Lb='selectingPermutation',Mb='com.google.gwt.xhr2.XMLHttpRequest2.devmode.js',Nb="GWT module 'com.google.gwt.xhr2.XMLHttpRequest2' may need to be (re)compiled",Ob=':',Pb=10,Qb='.cache.js',Rb='loadExternalRefs',Sb='end',Tb='http:',Ub='file:',Vb='_gwt_dummy_',Wb='__gwtDevModeHook:com.google.gwt.xhr2.XMLHttpRequest2',Xb='Ignoring non-whitelisted Dev Mode URL: ',Yb=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_google_gwt_xhr2_XMLHttpRequest2.__sendStats=r;com_google_gwt_xhr2_XMLHttpRequest2.__moduleName=S;com_google_gwt_xhr2_XMLHttpRequest2.__errFn=null;com_google_gwt_xhr2_XMLHttpRequest2.__moduleBase=U;com_google_gwt_xhr2_XMLHttpRequest2.__softPermutationId=V;com_google_gwt_xhr2_XMLHttpRequest2.__computePropValue=null;com_google_gwt_xhr2_XMLHttpRequest2.__getPropMap=null;com_google_gwt_xhr2_XMLHttpRequest2.__installRunAsyncCode=function(){};com_google_gwt_xhr2_XMLHttpRequest2.__gwtStartLoadingFragment=function(){return null};com_google_gwt_xhr2_XMLHttpRequest2.__gwt_isKnownPropertyValue=function(){return false};com_google_gwt_xhr2_XMLHttpRequest2.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};com_google_gwt_xhr2_XMLHttpRequest2.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[com_google_gwt_xhr2_XMLHttpRequest2.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
com_google_gwt_xhr2_XMLHttpRequest2.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(com_google_gwt_xhr2_XMLHttpRequest2.__errFn){n.onerror=function(){com_google_gwt_xhr2_XMLHttpRequest2.__errFn(nb,new Error(ob+code))}}p.getElementsByTagName(pb)[V].appendChild(n)}
com_google_gwt_xhr2_XMLHttpRequest2.__startLoadingFragment=function(a){return D(a)};com_google_gwt_xhr2_XMLHttpRequest2.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(qb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(rb),k;if(j){j=j.replace(sb,bb);if(j.indexOf(tb)>=V){continue}if(j==ub){k=i.getAttribute(vb);if(k){var l,m=k.indexOf(wb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==xb){k=i.getAttribute(vb);if(k){try{d=eval(k)}catch(a){alert(yb+k+zb)}}}else if(j==Ab){k=i.getAttribute(vb);if(k){try{e=eval(k)}catch(a){alert(yb+k+Bb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;com_google_gwt_xhr2_XMLHttpRequest2.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Cb);if(b==-1){b=a.length}var c=a.indexOf(Db);if(c==-1){c=a.length}var d=a.lastIndexOf(Eb,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Hb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Jb);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_google_gwt_xhr2_XMLHttpRequest2.__moduleBase+a}
function F(){var f=[];var g=V;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
__gwt_isKnownPropertyValue=function(a,b){return b in h[a]};com_google_gwt_xhr2_XMLHttpRequest2.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};com_google_gwt_xhr2_XMLHttpRequest2.__computePropValue=j;o.__gwt_activeModules[S].bindings=com_google_gwt_xhr2_XMLHttpRequest2.__getPropMap;r(O,Lb);if(q()){return D(Mb)}var k;try{alert(Nb);return;var l=k.indexOf(Ob);if(l!=-1){g=parseInt(k.substring(l+W),Pb);k=k.substring(V,l)}}catch(a){}com_google_gwt_xhr2_XMLHttpRequest2.__softPermutationId=g;return D(k+Qb)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Rb,P);r(Rb,Sb)}
B();com_google_gwt_xhr2_XMLHttpRequest2.__moduleBase=C();t[S].moduleBase=com_google_gwt_xhr2_XMLHttpRequest2.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==Tb||o.location.protocol==Ub);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Vb;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Wb;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Xb+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+Yb]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(pb)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Sb);A(H);return true}
com_google_gwt_xhr2_XMLHttpRequest2.succeeded=com_google_gwt_xhr2_XMLHttpRequest2();